/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    folders: Folder;
    tags: Tag;
    leads: Lead;
    blogCategories: BlogCategory;
    blogPosts: BlogPost;
    services: Service;
    caseStudies: CaseStudy;
    offers: Offer;
    testimonials: Testimonial;
    faqs: Faq;
    webapps: Webapp;
    stats: Stat;
    processSteps: ProcessStep;
    pricingPlans: PricingPlan;
    calculatorServices: CalculatorService;
    clients: Client;
    invoices: Invoice;
    'onboarding-guides': OnboardingGuide;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    folders: FoldersSelect<false> | FoldersSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    blogCategories: BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    blogPosts: BlogPostsSelect<false> | BlogPostsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    caseStudies: CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    webapps: WebappsSelect<false> | WebappsSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    processSteps: ProcessStepsSelect<false> | ProcessStepsSelect<true>;
    pricingPlans: PricingPlansSelect<false> | PricingPlansSelect<true>;
    calculatorServices: CalculatorServicesSelect<false> | CalculatorServicesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'onboarding-guides': OnboardingGuidesSelect<false> | OnboardingGuidesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    siteSettings: SiteSetting;
    homepage: Homepage;
    about: About;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders".
 */
export interface Folder {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  /**
   * Where this lead came from (e.g. Contact Form, Quote Calculator)
   */
  source?: string | null;
  name: string;
  email: string;
  message?: string | null;
  /**
   * Extra data like selected services or budget
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('new' | 'contacted' | 'converted' | 'archived') | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogCategories".
 */
export interface BlogCategory {
  id: number;
  title: string;
  /**
   * URL slug (e.g. digital-marketing)
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  /**
   * A short summary shown on blog listing cards (max ~160 chars)
   */
  excerpt?: string | null;
  /**
   * Write exactly what you want posted on LinkedIn (max 3000 chars).
   */
  linkedInPost?: string | null;
  coverImage?: (number | null) | Media;
  category?: (number | null) | BlogCategory;
  /**
   * PortableText JSON from Sanity
   */
  body?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publishedAt?: string | null;
  author?: string | null;
  /**
   * Meta description for search engines
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Raw SVG code for the icon
   */
  iconSvg?: string | null;
  body?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  tag?: string | null;
  description?: string | null;
  resultMetric?: string | null;
  resultText?: string | null;
  coverImage?: (number | null) | Media;
  body?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  imageGallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  videoGallery?:
    | {
        title?: string | null;
        videoUrl?: string | null;
        videoFile?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  title: string;
  slug: string;
  description: string;
  image?: (number | null) | Media;
  cta?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  authorName?: string | null;
  authorRole?: string | null;
  quote?: string | null;
  stars?: number | null;
  avatar?: (number | null) | Media;
  /**
   * Link to an external video (e.g. YouTube, Vimeo).
   */
  videoUrl?: string | null;
  /**
   * Upload a video file directly.
   */
  videoFile?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question?: string | null;
  answer?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webapps".
 */
export interface Webapp {
  id: number;
  name: string;
  tagline?: string | null;
  description?: string | null;
  status?: string | null;
  link?: string | null;
  order?: number | null;
  logo?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  value: string;
  label: string;
  prefix?: string | null;
  suffix?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processSteps".
 */
export interface ProcessStep {
  id: number;
  title: string;
  description?: string | null;
  stepNumber: number;
  iconSvg?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricingPlans".
 */
export interface PricingPlan {
  id: number;
  name: string;
  price: string;
  description?: string | null;
  isPopular?: boolean | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculatorServices".
 */
export interface CalculatorService {
  id: number;
  name: string;
  basePrice: number;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  clientName: string;
  slug: string;
  /**
   * The 6-digit code or phrase to log into the portal
   */
  accessCode: string;
  projectName?: string | null;
  projectStatus?: ('onboarding' | 'design' | 'development' | 'review' | 'completed' | 'retainer') | null;
  welcomeMessage?: string | null;
  onboardingGuide?: (number | null) | OnboardingGuide;
  timeline?:
    | {
        date: string;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  deliverables?:
    | {
        category?: ('design' | 'brand' | 'documents' | 'videos' | 'other') | null;
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-guides".
 */
export interface OnboardingGuide {
  id: number;
  title: string;
  description?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  invoiceId: string;
  client: number | Client;
  dateIssued?: string | null;
  dueDate?: string | null;
  status?: ('pending' | 'paid' | 'overdue') | null;
  currency?: string | null;
  taxRate?: number | null;
  items?:
    | {
        description: string;
        quantity: number;
        rate: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'folders';
        value: number | Folder;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'blogCategories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'blogPosts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'caseStudies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'webapps';
        value: number | Webapp;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null)
    | ({
        relationTo: 'processSteps';
        value: number | ProcessStep;
      } | null)
    | ({
        relationTo: 'pricingPlans';
        value: number | PricingPlan;
      } | null)
    | ({
        relationTo: 'calculatorServices';
        value: number | CalculatorService;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'onboarding-guides';
        value: number | OnboardingGuide;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders_select".
 */
export interface FoldersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  source?: T;
  name?: T;
  email?: T;
  message?: T;
  metadata?: T;
  status?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogCategories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  linkedInPost?: T;
  coverImage?: T;
  category?: T;
  body?: T;
  publishedAt?: T;
  author?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  iconSvg?: T;
  body?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tag?: T;
  description?: T;
  resultMetric?: T;
  resultText?: T;
  coverImage?: T;
  body?: T;
  imageGallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  videoGallery?:
    | T
    | {
        title?: T;
        videoUrl?: T;
        videoFile?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  cta?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  authorName?: T;
  authorRole?: T;
  quote?: T;
  stars?: T;
  avatar?: T;
  videoUrl?: T;
  videoFile?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webapps_select".
 */
export interface WebappsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  description?: T;
  status?: T;
  link?: T;
  order?: T;
  logo?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  prefix?: T;
  suffix?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processSteps_select".
 */
export interface ProcessStepsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  stepNumber?: T;
  iconSvg?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricingPlans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  description?: T;
  isPopular?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculatorServices_select".
 */
export interface CalculatorServicesSelect<T extends boolean = true> {
  name?: T;
  basePrice?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  clientName?: T;
  slug?: T;
  accessCode?: T;
  projectName?: T;
  projectStatus?: T;
  welcomeMessage?: T;
  onboardingGuide?: T;
  timeline?:
    | T
    | {
        date?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  deliverables?:
    | T
    | {
        category?: T;
        title?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceId?: T;
  client?: T;
  dateIssued?: T;
  dueDate?: T;
  status?: T;
  currency?: T;
  taxRate?: T;
  items?:
    | T
    | {
        description?: T;
        quantity?: T;
        rate?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-guides_select".
 */
export interface OnboardingGuidesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  title?: string | null;
  description?: string | null;
  email?: string | null;
  /**
   * Include country code, no spaces or + sign (e.g. 1234567890)
   */
  whatsappNumber?: string | null;
  socialLinks?:
    | {
        platform:
          | 'linkedin'
          | 'instagram'
          | 'twitter'
          | 'facebook'
          | 'youtube'
          | 'tiktok'
          | 'github'
          | 'behance'
          | 'dribbble'
          | 'threads'
          | 'pinterest'
          | 'snapchat'
          | 'other';
        url: string;
        /**
         * If you selected "Other", give it a name (e.g. "WhatsApp", "Discord")
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  footerTagline?: string | null;
  clientLogos?:
    | {
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  navLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  bankDetails?: {
    bankName?: string | null;
    accountName?: string | null;
    accountNumber?: string | null;
  };
  /**
   * Turn on to allow clients to pay invoices directly via Paystack.
   */
  enablePaystack?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroHeadline?: string | null;
  heroTagline?: string | null;
  heroServices?:
    | {
        service?: string | null;
        id?: string | null;
      }[]
    | null;
  founderTitle?: string | null;
  founderText?:
    | {
        paragraph?: string | null;
        id?: string | null;
      }[]
    | null;
  founderImage?: (number | null) | Media;
  newsletterHeading?: string | null;
  newsletterSubheading?: string | null;
  contactHeading?: string | null;
  contactSubheading?: string | null;
  contactInfoTitle?: string | null;
  contactInfoText?: string | null;
  contactWhatsappButtonText?: string | null;
  contactSubmitButtonText?: string | null;
  contactFormSuccessMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  title?: string | null;
  /**
   * The main headline for the about page
   */
  headline?: string | null;
  /**
   * Use newlines to separate paragraphs
   */
  bio?: string | null;
  /**
   * The mission statement of the business
   */
  mission?: string | null;
  /**
   * The vision statement of the business
   */
  vision?: string | null;
  founderImage?: (number | null) | Media;
  coreValues?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  email?: T;
  whatsappNumber?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  footerTagline?: T;
  clientLogos?:
    | T
    | {
        logo?: T;
        id?: T;
      };
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        id?: T;
      };
  bankDetails?:
    | T
    | {
        bankName?: T;
        accountName?: T;
        accountNumber?: T;
      };
  enablePaystack?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroHeadline?: T;
  heroTagline?: T;
  heroServices?:
    | T
    | {
        service?: T;
        id?: T;
      };
  founderTitle?: T;
  founderText?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  founderImage?: T;
  newsletterHeading?: T;
  newsletterSubheading?: T;
  contactHeading?: T;
  contactSubheading?: T;
  contactInfoTitle?: T;
  contactInfoText?: T;
  contactWhatsappButtonText?: T;
  contactSubmitButtonText?: T;
  contactFormSuccessMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  title?: T;
  headline?: T;
  bio?: T;
  mission?: T;
  vision?: T;
  founderImage?: T;
  coreValues?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}