/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    folders: Folder;
    tags: Tag;
    leads: Lead;
    blogCategories: BlogCategory;
    blogPosts: BlogPost;
    services: Service;
    caseStudies: CaseStudy;
    offers: Offer;
    testimonials: Testimonial;
    faqs: Faq;
    webapps: Webapp;
    stats: Stat;
    processSteps: ProcessStep;
    pricingPlans: PricingPlan;
    calculatorServices: CalculatorService;
    clients: Client;
    invoices: Invoice;
    'onboarding-guides': OnboardingGuide;
    'onboarding-documents': OnboardingDocument;
    pages: Page;
    emailCampaigns: EmailCampaign;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    folders: FoldersSelect<false> | FoldersSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    blogCategories: BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    blogPosts: BlogPostsSelect<false> | BlogPostsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    caseStudies: CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    webapps: WebappsSelect<false> | WebappsSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    processSteps: ProcessStepsSelect<false> | ProcessStepsSelect<true>;
    pricingPlans: PricingPlansSelect<false> | PricingPlansSelect<true>;
    calculatorServices: CalculatorServicesSelect<false> | CalculatorServicesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'onboarding-guides': OnboardingGuidesSelect<false> | OnboardingGuidesSelect<true>;
    'onboarding-documents': OnboardingDocumentsSelect<false> | OnboardingDocumentsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    emailCampaigns: EmailCampaignsSelect<false> | EmailCampaignsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    siteSettings: SiteSetting;
    homepage: Homepage;
    about: About;
    contactPage: ContactPage;
    servicesPage: ServicesPage;
    projectsPage: ProjectsPage;
    quaderpPage: QuaderpPage;
    videoProductionPage: VideoProductionPage;
    webDesignPage: WebDesignPage;
    brandIdentityPage: BrandIdentityPage;
    seoPage: SeoPage;
    brandStudioPage: BrandStudioPage;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    contactPage: ContactPageSelect<false> | ContactPageSelect<true>;
    servicesPage: ServicesPageSelect<false> | ServicesPageSelect<true>;
    projectsPage: ProjectsPageSelect<false> | ProjectsPageSelect<true>;
    quaderpPage: QuaderpPageSelect<false> | QuaderpPageSelect<true>;
    videoProductionPage: VideoProductionPageSelect<false> | VideoProductionPageSelect<true>;
    webDesignPage: WebDesignPageSelect<false> | WebDesignPageSelect<true>;
    brandIdentityPage: BrandIdentityPageSelect<false> | BrandIdentityPageSelect<true>;
    seoPage: SeoPageSelect<false> | SeoPageSelect<true>;
    brandStudioPage: BrandStudioPageSelect<false> | BrandStudioPageSelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Profile picture shown in the admin top bar.
   */
  avatar?: (number | null) | Media;
  /**
   * Shown in the admin dashboard greeting.
   */
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Set automatically by the mockup pipeline for AI-generated device mockups.
   */
  kind?: ('raw' | 'mockup') | null;
  /**
   * The raw image this mockup was generated from, when kind = Generated Mockup.
   */
  sourceImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders".
 */
export interface Folder {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  /**
   * Which entry point captured this lead.
   */
  source?: ('contact-form' | 'lead-magnet' | 'newsletter' | 'calculator' | 'whatsapp' | 'other') | null;
  /**
   * Name of the lead magnet they opted in for (e.g. "10-Point Website Audit Checklist").
   */
  magnetRequested?: string | null;
  name: string;
  email: string;
  message?: string | null;
  /**
   * Budget range selected on the contact form.
   */
  budget?: ('< $2,000' | '$2k - $5k' | '$5k - $10k' | '$10k+') | null;
  /**
   * Services selected on the contact form (array of strings).
   */
  servicesInterested?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Extra data like selected services or budget
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('new' | 'contacted' | 'qualified' | 'won' | 'lost' | 'archived') | null;
  /**
   * Auto-set when this lead is marked Won — links to the Client record created from it.
   */
  convertedClient?: (number | null) | Client;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  clientName: string;
  contactName?: string | null;
  clientEmail?: string | null;
  phone?: string | null;
  service?:
    | (
        | 'web-design'
        | 'digital-marketing'
        | 'branding'
        | 'video-production'
        | 'seo-paid-ads'
        | 'social-media'
        | 'multiple'
      )
    | null;
  package?: string | null;
  price?: number | null;
  startDate?: string | null;
  pipelineStatus?:
    | ('lead' | 'discovery' | 'proposal' | 'negotiating' | 'won' | 'lost' | 'on-hold' | 'active' | 'completed')
    | null;
  source?: ('website' | 'whatsapp' | 'referral' | 'social' | 'walk-in' | 'other') | null;
  /**
   * Automatically updated when docs are sent via Make.com
   */
  documentsSent?: {
    contract?: boolean | null;
    invoice?: boolean | null;
    onboardingEmail?: boolean | null;
    setupInstructions?: boolean | null;
  };
  /**
   * Google Drive or shared URL for the proposal sent to this client
   */
  proposalUrl?: string | null;
  notes?: string | null;
  slug: string;
  /**
   * The 6-digit code or phrase to log into the portal
   */
  accessCode: string;
  projectName?: string | null;
  projectStatus?: ('onboarding' | 'design' | 'development' | 'review' | 'completed' | 'retainer') | null;
  welcomeMessage?: string | null;
  onboardingGuide?: (number | null) | OnboardingGuide;
  timeline?:
    | {
        date: string;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  deliverables?:
    | {
        category?: ('design' | 'brand' | 'documents' | 'videos' | 'other') | null;
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Override document defaults for this client. Blank fields use standard values.
   */
  customizations?: {
    duration?: number | null;
    revisions?: number | null;
    depositPercent?: number | null;
    numberOfPages?: number | null;
    postsPerMonth?: number | null;
    platforms?: string | null;
    paymentTerms?: string | null;
    extraDeliverables?: string | null;
    specialTerms?: string | null;
  };
  /**
   * Optional personal notes injected into each automated email. Blank = standard template.
   */
  emailNotes?: {
    /**
     * Appears as a highlighted block in the first email.
     */
    welcome?: string | null;
    /**
     * Appears in the contract email, above the action-required block.
     */
    contract?: string | null;
    /**
     * Appears in the setup email, to clarify anything agreed verbally.
     */
    setup?: string | null;
    /**
     * Appears in the 7-day follow-up email.
     */
    checkin?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-guides".
 */
export interface OnboardingGuide {
  id: number;
  title: string;
  description?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogCategories".
 */
export interface BlogCategory {
  id: number;
  title: string;
  /**
   * URL slug (e.g. digital-marketing)
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  /**
   * A short summary shown on blog listing cards (max ~160 chars)
   */
  excerpt?: string | null;
  /**
   * Write exactly what you want posted on LinkedIn (max 3000 chars).
   */
  linkedInPost?: string | null;
  coverImage?: (number | null) | Media;
  category?: (number | null) | BlogCategory;
  /**
   * Legacy Sanity portable text. Do not edit. Use the Content field below instead.
   */
  body?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  author?: string | null;
  /**
   * Meta description for search engines
   */
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Raw SVG code for the icon
   */
  iconSvg?: string | null;
  body?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  order?: number | null;
  featuredImage?: (number | null) | Media;
  /**
   * Image shown on the service page hero.
   */
  rawMedia?: (number | null) | Media;
  /**
   * Optional device-mockup image to show instead of the raw hero media.
   */
  mockupMedia?: (number | null) | Media;
  mockupStatus?: ('pending' | 'processing' | 'ready' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  tag?: string | null;
  description?: string | null;
  resultMetric?: string | null;
  resultText?: string | null;
  coverImage?: (number | null) | Media;
  body?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  imageGallery?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  videoGallery?:
    | {
        title?: string | null;
        videoUrl?: string | null;
        videoFile?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  /**
   * Displayed as a badge on the site. "Concept" means no real client relationship.
   */
  projectType?: ('client' | 'concept' | 'self') | null;
  /**
   * Only publish when the entry is real and complete.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  title: string;
  slug: string;
  description: string;
  image?: (number | null) | Media;
  cta?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  authorName?: string | null;
  authorRole?: string | null;
  quote?: string | null;
  stars?: number | null;
  avatar?: (number | null) | Media;
  /**
   * Link to an external video (e.g. YouTube, Vimeo).
   */
  videoUrl?: string | null;
  /**
   * Upload a video file directly.
   */
  videoFile?: (number | null) | Media;
  order?: number | null;
  /**
   * Only check once this is a real client testimonial, not placeholder data.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question?: string | null;
  answer?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webapps".
 */
export interface Webapp {
  id: number;
  name: string;
  tagline?: string | null;
  description?: string | null;
  status?: string | null;
  link?: string | null;
  order?: number | null;
  logo?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  value: string;
  label: string;
  prefix?: string | null;
  suffix?: string | null;
  order?: number | null;
  /**
   * Uncheck to hide this stat from the site until it reflects a real number.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processSteps".
 */
export interface ProcessStep {
  id: number;
  title: string;
  description?: string | null;
  stepNumber: number;
  iconSvg?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricingPlans".
 */
export interface PricingPlan {
  id: number;
  name: string;
  price: string;
  /**
   * Base price in US Dollars. Shown to visitors outside Ghana and used for live currency conversion.
   */
  priceUSD?: number | null;
  /**
   * Fixed price in Ghana Cedis. Shown to visitors in Ghana.
   */
  priceGHS?: number | null;
  /**
   * Optional text label shown instead of a number (e.g. "Custom", "Retainer"). If set, this overrides the numeric prices on the card.
   */
  priceLabel?: string | null;
  /**
   * e.g. "/mo", "/yr", or leave empty for one-time pricing.
   */
  billingCycle?: string | null;
  description?: string | null;
  isPopular?: boolean | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * CTA button text, e.g. "Get Started", "Book a Call"
   */
  buttonText?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculatorServices".
 */
export interface CalculatorService {
  id: number;
  name: string;
  basePrice: number;
  /**
   * Price shown to visitors outside Ghana, in US Dollars. Not converted — set it deliberately.
   */
  priceUSD: number;
  /**
   * Price shown to visitors in Ghana, in Cedis. Not converted — set it deliberately.
   */
  priceGHS: number;
  /**
   * e.g. "/mo", "/yr", or leave empty for one-time pricing.
   */
  billingCycle?: string | null;
  description?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  invoiceId: string;
  client: number | Client;
  dateIssued?: string | null;
  dueDate?: string | null;
  status?: ('pending' | 'paid' | 'overdue') | null;
  currency?: string | null;
  taxRate?: number | null;
  items?:
    | {
        description: string;
        quantity: number;
        rate: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-generated. Forms part of the invoice link; without it the page 404s.
   */
  accessToken?: string | null;
  tokenIssuedAt?: string | null;
  /**
   * Authoritative total in minor units (e.g. pesewas). Recomputed on save; settlement compares Paystack against this, never against a figure from the browser.
   */
  amountMinor?: number | null;
  paidAt?: string | null;
  /**
   * Idempotency key. A reference can settle exactly one invoice, once.
   */
  paystackReference?: string | null;
  /**
   * What Paystack actually collected.
   */
  paystackAmountMinor?: number | null;
  paystackStatus?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-documents".
 */
export interface OnboardingDocument {
  id: number;
  /**
   * Which client is this document for?
   */
  client: number | Client;
  documentType: 'sla' | 'guide' | 'setup' | 'combined' | 'other';
  /**
   * Indicates if an AI email draft was successfully generated for this document.
   */
  emailDraftGenerated?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  pageBuilder?:
    | (
        | HeroSectionBlock
        | TextBlockBlock
        | ImageGalleryBlock
        | CallToActionBlock
        | FeatureGridBlock
        | TestimonialSliderBlock
        | FAQAccordionBlock
        | VideoEmbedBlock
        | PricingCardsBlock
        | TeamGridBlock
        | LogoCloudBlock
        | MediaAndTextBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSectionBlock".
 */
export interface HeroSectionBlock {
  heading: string;
  subheading?: string | null;
  backgroundImage?: (number | null) | Media;
  buttons?:
    | {
        label: string;
        url: string;
        style?: ('primary' | 'secondary' | 'outline') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlockBlock".
 */
export interface TextBlockBlock {
  heading?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content_html?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock".
 */
export interface ImageGalleryBlock {
  heading?: string | null;
  layout?: ('grid' | 'masonry' | 'carousel') | null;
  images: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  heading: string;
  text?: string | null;
  buttons?:
    | {
        label: string;
        url: string;
        style?: ('primary' | 'secondary' | 'outline') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  heading: string;
  subheading?: string | null;
  features: {
    icon?: (number | null) | Media;
    title: string;
    description: string;
    link?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialSliderBlock".
 */
export interface TestimonialSliderBlock {
  heading?: string | null;
  testimonials: {
    quote: string;
    authorName: string;
    authorRole?: string | null;
    authorImage?: (number | null) | Media;
    companyLogo?: (number | null) | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonialSlider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQAccordionBlock".
 */
export interface FAQAccordionBlock {
  heading: string;
  subheading?: string | null;
  faqs: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faqAccordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock".
 */
export interface VideoEmbedBlock {
  heading?: string | null;
  /**
   * YouTube or Vimeo URL
   */
  videoUrl: string;
  caption?: string | null;
  /**
   * Custom placeholder image before playing
   */
  thumbnailImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingCardsBlock".
 */
export interface PricingCardsBlock {
  heading: string;
  subheading?: string | null;
  cards: {
    tierName: string;
    price: string;
    /**
     * e.g. /month
     */
    billingPeriod?: string | null;
    description?: string | null;
    features?:
      | {
          feature?: string | null;
          id?: string | null;
        }[]
      | null;
    buttonLabel: string;
    buttonUrl: string;
    isPopular?: boolean | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricingCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamGridBlock".
 */
export interface TeamGridBlock {
  heading: string;
  subheading?: string | null;
  members: {
    image?: (number | null) | Media;
    name: string;
    role: string;
    bio?: string | null;
    linkedinUrl?: string | null;
    twitterUrl?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'teamGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock".
 */
export interface LogoCloudBlock {
  /**
   * e.g. Trusted by innovative companies
   */
  heading?: string | null;
  logos: {
    logo: number | Media;
    companyName?: string | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoCloud';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaAndTextBlock".
 */
export interface MediaAndTextBlock {
  mediaAlignment?: ('left' | 'right') | null;
  media: number | Media;
  heading?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content_html?: string | null;
  buttons?:
    | {
        label: string;
        url: string;
        style?: ('primary' | 'secondary' | 'outline') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaAndText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailCampaigns".
 */
export interface EmailCampaign {
  id: number;
  client?: (number | null) | Client;
  subject: string;
  previewText?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body_html?: string | null;
  ctaText?: string | null;
  ctaUrl?: string | null;
  status?: ('draft' | 'sent') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'folders';
        value: number | Folder;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'blogCategories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'blogPosts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'caseStudies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'webapps';
        value: number | Webapp;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null)
    | ({
        relationTo: 'processSteps';
        value: number | ProcessStep;
      } | null)
    | ({
        relationTo: 'pricingPlans';
        value: number | PricingPlan;
      } | null)
    | ({
        relationTo: 'calculatorServices';
        value: number | CalculatorService;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'onboarding-guides';
        value: number | OnboardingGuide;
      } | null)
    | ({
        relationTo: 'onboarding-documents';
        value: number | OnboardingDocument;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'emailCampaigns';
        value: number | EmailCampaign;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  avatar?: T;
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  kind?: T;
  sourceImage?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "folders_select".
 */
export interface FoldersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  source?: T;
  magnetRequested?: T;
  name?: T;
  email?: T;
  message?: T;
  budget?: T;
  servicesInterested?: T;
  metadata?: T;
  status?: T;
  convertedClient?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogCategories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  linkedInPost?: T;
  coverImage?: T;
  category?: T;
  body?: T;
  content?: T;
  publishedAt?: T;
  author?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  iconSvg?: T;
  body?: T;
  order?: T;
  featuredImage?: T;
  rawMedia?: T;
  mockupMedia?: T;
  mockupStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tag?: T;
  description?: T;
  resultMetric?: T;
  resultText?: T;
  coverImage?: T;
  body?: T;
  imageGallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  videoGallery?:
    | T
    | {
        title?: T;
        videoUrl?: T;
        videoFile?: T;
        id?: T;
      };
  order?: T;
  projectType?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  image?: T;
  cta?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  authorName?: T;
  authorRole?: T;
  quote?: T;
  stars?: T;
  avatar?: T;
  videoUrl?: T;
  videoFile?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webapps_select".
 */
export interface WebappsSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  description?: T;
  status?: T;
  link?: T;
  order?: T;
  logo?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  prefix?: T;
  suffix?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processSteps_select".
 */
export interface ProcessStepsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  stepNumber?: T;
  iconSvg?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricingPlans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  priceUSD?: T;
  priceGHS?: T;
  priceLabel?: T;
  billingCycle?: T;
  description?: T;
  isPopular?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  buttonText?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculatorServices_select".
 */
export interface CalculatorServicesSelect<T extends boolean = true> {
  name?: T;
  basePrice?: T;
  priceUSD?: T;
  priceGHS?: T;
  billingCycle?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  clientName?: T;
  contactName?: T;
  clientEmail?: T;
  phone?: T;
  service?: T;
  package?: T;
  price?: T;
  startDate?: T;
  pipelineStatus?: T;
  source?: T;
  documentsSent?:
    | T
    | {
        contract?: T;
        invoice?: T;
        onboardingEmail?: T;
        setupInstructions?: T;
      };
  proposalUrl?: T;
  notes?: T;
  slug?: T;
  accessCode?: T;
  projectName?: T;
  projectStatus?: T;
  welcomeMessage?: T;
  onboardingGuide?: T;
  timeline?:
    | T
    | {
        date?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  deliverables?:
    | T
    | {
        category?: T;
        title?: T;
        url?: T;
        id?: T;
      };
  customizations?:
    | T
    | {
        duration?: T;
        revisions?: T;
        depositPercent?: T;
        numberOfPages?: T;
        postsPerMonth?: T;
        platforms?: T;
        paymentTerms?: T;
        extraDeliverables?: T;
        specialTerms?: T;
      };
  emailNotes?:
    | T
    | {
        welcome?: T;
        contract?: T;
        setup?: T;
        checkin?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceId?: T;
  client?: T;
  dateIssued?: T;
  dueDate?: T;
  status?: T;
  currency?: T;
  taxRate?: T;
  items?:
    | T
    | {
        description?: T;
        quantity?: T;
        rate?: T;
        id?: T;
      };
  accessToken?: T;
  tokenIssuedAt?: T;
  amountMinor?: T;
  paidAt?: T;
  paystackReference?: T;
  paystackAmountMinor?: T;
  paystackStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-guides_select".
 */
export interface OnboardingGuidesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-documents_select".
 */
export interface OnboardingDocumentsSelect<T extends boolean = true> {
  client?: T;
  documentType?: T;
  emailDraftGenerated?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageBuilder?:
    | T
    | {
        heroSection?: T | HeroSectionBlockSelect<T>;
        textBlock?: T | TextBlockBlockSelect<T>;
        imageGallery?: T | ImageGalleryBlockSelect<T>;
        callToAction?: T | CallToActionBlockSelect<T>;
        featureGrid?: T | FeatureGridBlockSelect<T>;
        testimonialSlider?: T | TestimonialSliderBlockSelect<T>;
        faqAccordion?: T | FAQAccordionBlockSelect<T>;
        videoEmbed?: T | VideoEmbedBlockSelect<T>;
        pricingCards?: T | PricingCardsBlockSelect<T>;
        teamGrid?: T | TeamGridBlockSelect<T>;
        logoCloud?: T | LogoCloudBlockSelect<T>;
        mediaAndText?: T | MediaAndTextBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSectionBlock_select".
 */
export interface HeroSectionBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  backgroundImage?: T;
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlockBlock_select".
 */
export interface TextBlockBlockSelect<T extends boolean = true> {
  heading?: T;
  content?: T;
  content_html?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock_select".
 */
export interface ImageGalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  layout?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialSliderBlock_select".
 */
export interface TestimonialSliderBlockSelect<T extends boolean = true> {
  heading?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        authorName?: T;
        authorRole?: T;
        authorImage?: T;
        companyLogo?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQAccordionBlock_select".
 */
export interface FAQAccordionBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock_select".
 */
export interface VideoEmbedBlockSelect<T extends boolean = true> {
  heading?: T;
  videoUrl?: T;
  caption?: T;
  thumbnailImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingCardsBlock_select".
 */
export interface PricingCardsBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  cards?:
    | T
    | {
        tierName?: T;
        price?: T;
        billingPeriod?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        buttonLabel?: T;
        buttonUrl?: T;
        isPopular?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamGridBlock_select".
 */
export interface TeamGridBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  members?:
    | T
    | {
        image?: T;
        name?: T;
        role?: T;
        bio?: T;
        linkedinUrl?: T;
        twitterUrl?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock_select".
 */
export interface LogoCloudBlockSelect<T extends boolean = true> {
  heading?: T;
  logos?:
    | T
    | {
        logo?: T;
        companyName?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaAndTextBlock_select".
 */
export interface MediaAndTextBlockSelect<T extends boolean = true> {
  mediaAlignment?: T;
  media?: T;
  heading?: T;
  content?: T;
  content_html?: T;
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailCampaigns_select".
 */
export interface EmailCampaignsSelect<T extends boolean = true> {
  client?: T;
  subject?: T;
  previewText?: T;
  body?: T;
  body_html?: T;
  ctaText?: T;
  ctaUrl?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  title?: string | null;
  description?: string | null;
  email?: string | null;
  /**
   * Include country code, no spaces or + sign (e.g. 233530890302)
   */
  whatsappNumber?: string | null;
  /**
   * Default message pre-filled when a visitor taps any WhatsApp CTA.
   */
  whatsappMessage?: string | null;
  socialLinks?:
    | {
        platform:
          | 'linkedin'
          | 'instagram'
          | 'twitter'
          | 'facebook'
          | 'youtube'
          | 'tiktok'
          | 'github'
          | 'behance'
          | 'dribbble'
          | 'threads'
          | 'pinterest'
          | 'snapchat'
          | 'other';
        url: string;
        /**
         * If you selected "Other", give it a name (e.g. "WhatsApp", "Discord")
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  footerTagline?: string | null;
  clientLogos?:
    | {
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  navLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Only add badges you have genuinely earned. Displayed in the footer and About page.
   */
  certifications?:
    | {
        badge: number | Media;
        /**
         * e.g. "Google Ads Certified"
         */
        label: string;
        /**
         * URL where visitors can verify this credential.
         */
        verifyLink?: string | null;
        id?: string | null;
      }[]
    | null;
  bankDetails?: {
    bankName?: string | null;
    accountName?: string | null;
    accountNumber?: string | null;
  };
  /**
   * Turn on to allow clients to pay invoices directly via Paystack.
   */
  enablePaystack?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroHeadline?: string | null;
  heroTagline?: string | null;
  /**
   * Supporting sentence beneath the tagline — founder-led, honest tone.
   */
  heroSubheadline?: string | null;
  primaryCta?: {
    label?: string | null;
    link?: string | null;
  };
  secondaryCta?: {
    label?: string | null;
    link?: string | null;
  };
  heroServices?:
    | {
        /**
         * Replaces the default text before the highlighted word for this specific service.
         */
        prefix?: string | null;
        service?: string | null;
        /**
         * Replaces the default text after the highlighted word for this specific service.
         */
        suffix?: string | null;
        /**
         * Image/video shown in the hero.
         */
        rawMedia?: (number | null) | Media;
        /**
         * Optional device-mockup image to show instead of the raw service media.
         */
        mockupMedia?: (number | null) | Media;
        mockupStatus?: ('pending' | 'processing' | 'ready' | 'failed') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Only enable once the Stats collection has real, verified numbers.
   */
  showStats?: boolean | null;
  /**
   * 3–4 short value cards shown in place of the stats counter. E.g. "Direct Founder Access / Built for Ghana / Results-Focused".
   */
  trustHighlights?:
    | {
        icon?: string | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The strip under the hero. It removes the buyer's risk — say what they get and what protects them. Do NOT frame it around being new or unproven ("we're early", "bet on our hunger"): that reads as inexperience and costs conversions. State the guarantee with confidence instead.
   */
  riskReversal?: {
    enabled?: boolean | null;
    heading?: string | null;
    body?: string | null;
  };
  founderTitle?: string | null;
  founderText?:
    | {
        paragraph?: string | null;
        id?: string | null;
      }[]
    | null;
  founderImage?: (number | null) | Media;
  newsletterHeading?: string | null;
  newsletterSubheading?: string | null;
  contactHeading?: string | null;
  contactSubheading?: string | null;
  contactInfoTitle?: string | null;
  contactInfoText?: string | null;
  contactWhatsappButtonText?: string | null;
  contactSubmitButtonText?: string | null;
  contactFormSuccessMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  title?: string | null;
  /**
   * Your real name — used in headings, bio, and any auto-generated text referencing the founder.
   */
  founderName?: string | null;
  /**
   * The main headline for the about page
   */
  headline?: string | null;
  /**
   * One supporting sentence under the headline.
   */
  subheadline?: string | null;
  /**
   * Use newlines to separate paragraphs
   */
  bio?: string | null;
  /**
   * The mission statement of the business
   */
  mission?: string | null;
  /**
   * The vision statement of the business
   */
  vision?: string | null;
  founderImage?: (number | null) | Media;
  coreValues?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage".
 */
export interface ContactPage {
  id: number;
  heroHeading?: string | null;
  heroSubtitle?: string | null;
  contactSubtitle?: string | null;
  contactText?: string | null;
  whatsappButtonText?: string | null;
  whatsappMessage?: string | null;
  formSuccessMessage?: string | null;
  submitButtonText?: string | null;
  bookingDividerText?: string | null;
  bookingHeading?: string | null;
  bookingSubtitle?: string | null;
  calendlyUrl?: string | null;
  showBookingSection?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage".
 */
export interface ServicesPage {
  id: number;
  title?: string | null;
  description?: string | null;
  heading?: string | null;
  subheading?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectsPage".
 */
export interface ProjectsPage {
  id: number;
  title?: string | null;
  description?: string | null;
  heading?: string | null;
  subheading?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quaderpPage".
 */
export interface QuaderpPage {
  id: number;
  heroBadge?: string | null;
  heroTitle?: string | null;
  heroTitleGradient?: string | null;
  heroSubtitle?: string | null;
  trustBadges?:
    | {
        badge?: string | null;
        id?: string | null;
      }[]
    | null;
  featuresHeading?: string | null;
  featuresSubtitle?: string | null;
  features?:
    | {
        title?: string | null;
        description?: string | null;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  showcaseHeading?: string | null;
  showcaseItems?:
    | {
        label?: string | null;
        heading?: string | null;
        headingGradient?: string | null;
        description?: string | null;
        bulletPoints?:
          | {
              point?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  pricingHeading?: string | null;
  pricingSubtitle?: string | null;
  pricingPlans?:
    | {
        name?: string | null;
        price?: string | null;
        period?: string | null;
        description?: string | null;
        features?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        isPopular?: boolean | null;
        buttonText?: string | null;
        id?: string | null;
      }[]
    | null;
  pricingNote?: string | null;
  contactHeading?: string | null;
  contactSubtitle?: string | null;
  formspreeEndpoint?: string | null;
  calendlyUrl?: string | null;
  whatsappNumber?: string | null;
  whatsappMessage?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videoProductionPage".
 */
export interface VideoProductionPage {
  id: number;
  hero?: {
    badge?: string | null;
    headline?: string | null;
    subtitle?: string | null;
    primaryCtaText?: string | null;
    secondaryCtaText?: string | null;
    /**
     * Hero image or video
     */
    media?: (number | null) | Media;
  };
  servicesSection?: {
    heading?: string | null;
    subtitle?: string | null;
    services?:
      | {
          title?: string | null;
          description?: string | null;
          /**
           * Paste SVG code here
           */
          iconSvg?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  showreel?: {
    heading?: string | null;
    subtitle?: string | null;
    /**
     * YouTube or Vimeo URL
     */
    videoUrl?: string | null;
    isComingSoon?: boolean | null;
  };
  portfolioGallery?: {
    heading?: string | null;
    subtitle?: string | null;
    images?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  processSection?: {
    heading?: string | null;
    subtitle?: string | null;
    steps?:
      | {
          /**
           * e.g. 01
           */
          number?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  pricingSection?: {
    heading?: string | null;
    subtitle?: string | null;
    note?: string | null;
    plans?:
      | {
          name: string;
          price: string;
          period?: string | null;
          description?: string | null;
          isPopular?: boolean | null;
          features?:
            | {
                feature?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  faqSection?: {
    heading?: string | null;
    subtitle?: string | null;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  ctaSection?: {
    heading?: string | null;
    subtitle?: string | null;
    primaryButtonText?: string | null;
    whatsappButtonText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webDesignPage".
 */
export interface WebDesignPage {
  id: number;
  hero?: {
    badge?: string | null;
    headline?: string | null;
    subtitle?: string | null;
    primaryCtaText?: string | null;
    secondaryCtaText?: string | null;
    /**
     * Hero image or video
     */
    media?: (number | null) | Media;
  };
  servicesSection?: {
    heading?: string | null;
    subtitle?: string | null;
    services?:
      | {
          title?: string | null;
          description?: string | null;
          /**
           * Paste SVG code here
           */
          iconSvg?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  showreel?: {
    heading?: string | null;
    subtitle?: string | null;
    /**
     * YouTube or Vimeo URL
     */
    videoUrl?: string | null;
    isComingSoon?: boolean | null;
  };
  portfolioGallery?: {
    heading?: string | null;
    subtitle?: string | null;
    images?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  processSection?: {
    heading?: string | null;
    subtitle?: string | null;
    steps?:
      | {
          /**
           * e.g. 01
           */
          number?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  pricingSection?: {
    heading?: string | null;
    subtitle?: string | null;
    note?: string | null;
    plans?:
      | {
          name: string;
          price: string;
          period?: string | null;
          description?: string | null;
          isPopular?: boolean | null;
          features?:
            | {
                feature?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  faqSection?: {
    heading?: string | null;
    subtitle?: string | null;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  ctaSection?: {
    heading?: string | null;
    subtitle?: string | null;
    primaryButtonText?: string | null;
    whatsappButtonText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brandIdentityPage".
 */
export interface BrandIdentityPage {
  id: number;
  hero?: {
    badge?: string | null;
    headline?: string | null;
    subtitle?: string | null;
    primaryCtaText?: string | null;
    secondaryCtaText?: string | null;
    /**
     * Hero image or video
     */
    media?: (number | null) | Media;
  };
  servicesSection?: {
    heading?: string | null;
    subtitle?: string | null;
    services?:
      | {
          title?: string | null;
          description?: string | null;
          /**
           * Paste SVG code here
           */
          iconSvg?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  showreel?: {
    heading?: string | null;
    subtitle?: string | null;
    /**
     * YouTube or Vimeo URL
     */
    videoUrl?: string | null;
    isComingSoon?: boolean | null;
  };
  portfolioGallery?: {
    heading?: string | null;
    subtitle?: string | null;
    images?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  processSection?: {
    heading?: string | null;
    subtitle?: string | null;
    steps?:
      | {
          /**
           * e.g. 01
           */
          number?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  pricingSection?: {
    heading?: string | null;
    subtitle?: string | null;
    note?: string | null;
    plans?:
      | {
          name: string;
          price: string;
          period?: string | null;
          description?: string | null;
          isPopular?: boolean | null;
          features?:
            | {
                feature?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  faqSection?: {
    heading?: string | null;
    subtitle?: string | null;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  ctaSection?: {
    heading?: string | null;
    subtitle?: string | null;
    primaryButtonText?: string | null;
    whatsappButtonText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seoPage".
 */
export interface SeoPage {
  id: number;
  hero?: {
    badge?: string | null;
    headline?: string | null;
    subtitle?: string | null;
    primaryCtaText?: string | null;
    secondaryCtaText?: string | null;
    /**
     * Hero image or video
     */
    media?: (number | null) | Media;
  };
  servicesSection?: {
    heading?: string | null;
    subtitle?: string | null;
    services?:
      | {
          title?: string | null;
          description?: string | null;
          /**
           * Paste SVG code here
           */
          iconSvg?: string | null;
          features?:
            | {
                feature?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  portfolioGallery?: {
    heading?: string | null;
    subtitle?: string | null;
    images?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  processSection?: {
    heading?: string | null;
    subtitle?: string | null;
    steps?:
      | {
          /**
           * e.g. 1
           */
          number?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  pricingSection?: {
    heading?: string | null;
    subtitle?: string | null;
    note?: string | null;
    plans?:
      | {
          name: string;
          price: string;
          period?: string | null;
          description?: string | null;
          isPopular?: boolean | null;
          features?:
            | {
                feature?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  faqSection?: {
    heading?: string | null;
    subtitle?: string | null;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  ctaSection?: {
    heading?: string | null;
    subtitle?: string | null;
    primaryButtonText?: string | null;
    whatsappButtonText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brandStudioPage".
 */
export interface BrandStudioPage {
  id: number;
  /**
   * Browser tab + search result title (SEO).
   */
  title?: string | null;
  /**
   * Meta description shown in search results (SEO).
   */
  description?: string | null;
  settings?: {
    /**
     * Overrides the site WhatsApp number for this page. Leave blank to use Site Settings.
     */
    whatsappNumber?: string | null;
    calendlyUrl?: string | null;
  };
  hero?: {
    eyebrow?: string | null;
    headingTop?: string | null;
    /**
     * Shown in the gradient accent colour.
     */
    headingAccent?: string | null;
    subheading?: string | null;
    primaryCtaText?: string | null;
    secondaryCtaText?: string | null;
    trustText?: string | null;
  };
  howSection?: {
    heading?: string | null;
    subheading?: string | null;
    steps?:
      | {
          /**
           * e.g. 1
           */
          number?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  pricingSection?: {
    heading?: string | null;
    subheading?: string | null;
    /**
     * Shown after a bold "Add-ons:" label.
     */
    addonsText?: string | null;
    unsureText?: string | null;
    /**
     * Price is shown as "GHS {price}/mo" — enter just the number, e.g. 1,800.
     */
    plans?:
      | {
          name: string;
          price: string;
          blurb?: string | null;
          isPopular?: boolean | null;
          ctaText?: string | null;
          features?:
            | {
                feature?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  whySection?: {
    heading?: string | null;
    items?:
      | {
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  faqSection?: {
    heading?: string | null;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  finalCta?: {
    heading?: string | null;
    subheading?: string | null;
    primaryCtaText?: string | null;
    whatsappCtaText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  email?: T;
  whatsappNumber?: T;
  whatsappMessage?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  footerTagline?: T;
  clientLogos?:
    | T
    | {
        logo?: T;
        id?: T;
      };
  navLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        id?: T;
      };
  certifications?:
    | T
    | {
        badge?: T;
        label?: T;
        verifyLink?: T;
        id?: T;
      };
  bankDetails?:
    | T
    | {
        bankName?: T;
        accountName?: T;
        accountNumber?: T;
      };
  enablePaystack?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroHeadline?: T;
  heroTagline?: T;
  heroSubheadline?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        link?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        link?: T;
      };
  heroServices?:
    | T
    | {
        prefix?: T;
        service?: T;
        suffix?: T;
        rawMedia?: T;
        mockupMedia?: T;
        mockupStatus?: T;
        id?: T;
      };
  showStats?: T;
  trustHighlights?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  riskReversal?:
    | T
    | {
        enabled?: T;
        heading?: T;
        body?: T;
      };
  founderTitle?: T;
  founderText?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  founderImage?: T;
  newsletterHeading?: T;
  newsletterSubheading?: T;
  contactHeading?: T;
  contactSubheading?: T;
  contactInfoTitle?: T;
  contactInfoText?: T;
  contactWhatsappButtonText?: T;
  contactSubmitButtonText?: T;
  contactFormSuccessMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  title?: T;
  founderName?: T;
  headline?: T;
  subheadline?: T;
  bio?: T;
  mission?: T;
  vision?: T;
  founderImage?: T;
  coreValues?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heroHeading?: T;
  heroSubtitle?: T;
  contactSubtitle?: T;
  contactText?: T;
  whatsappButtonText?: T;
  whatsappMessage?: T;
  formSuccessMessage?: T;
  submitButtonText?: T;
  bookingDividerText?: T;
  bookingHeading?: T;
  bookingSubtitle?: T;
  calendlyUrl?: T;
  showBookingSection?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  heading?: T;
  subheading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projectsPage_select".
 */
export interface ProjectsPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  heading?: T;
  subheading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quaderpPage_select".
 */
export interface QuaderpPageSelect<T extends boolean = true> {
  heroBadge?: T;
  heroTitle?: T;
  heroTitleGradient?: T;
  heroSubtitle?: T;
  trustBadges?:
    | T
    | {
        badge?: T;
        id?: T;
      };
  featuresHeading?: T;
  featuresSubtitle?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  showcaseHeading?: T;
  showcaseItems?:
    | T
    | {
        label?: T;
        heading?: T;
        headingGradient?: T;
        description?: T;
        bulletPoints?:
          | T
          | {
              point?: T;
              id?: T;
            };
        id?: T;
      };
  pricingHeading?: T;
  pricingSubtitle?: T;
  pricingPlans?:
    | T
    | {
        name?: T;
        price?: T;
        period?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        isPopular?: T;
        buttonText?: T;
        id?: T;
      };
  pricingNote?: T;
  contactHeading?: T;
  contactSubtitle?: T;
  formspreeEndpoint?: T;
  calendlyUrl?: T;
  whatsappNumber?: T;
  whatsappMessage?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videoProductionPage_select".
 */
export interface VideoProductionPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        headline?: T;
        subtitle?: T;
        primaryCtaText?: T;
        secondaryCtaText?: T;
        media?: T;
      };
  servicesSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        services?:
          | T
          | {
              title?: T;
              description?: T;
              iconSvg?: T;
              id?: T;
            };
      };
  showreel?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        videoUrl?: T;
        isComingSoon?: T;
      };
  portfolioGallery?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  processSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        steps?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  pricingSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        note?: T;
        plans?:
          | T
          | {
              name?: T;
              price?: T;
              period?: T;
              description?: T;
              isPopular?: T;
              features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  faqSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        primaryButtonText?: T;
        whatsappButtonText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webDesignPage_select".
 */
export interface WebDesignPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        headline?: T;
        subtitle?: T;
        primaryCtaText?: T;
        secondaryCtaText?: T;
        media?: T;
      };
  servicesSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        services?:
          | T
          | {
              title?: T;
              description?: T;
              iconSvg?: T;
              id?: T;
            };
      };
  showreel?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        videoUrl?: T;
        isComingSoon?: T;
      };
  portfolioGallery?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  processSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        steps?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  pricingSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        note?: T;
        plans?:
          | T
          | {
              name?: T;
              price?: T;
              period?: T;
              description?: T;
              isPopular?: T;
              features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  faqSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        primaryButtonText?: T;
        whatsappButtonText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brandIdentityPage_select".
 */
export interface BrandIdentityPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        headline?: T;
        subtitle?: T;
        primaryCtaText?: T;
        secondaryCtaText?: T;
        media?: T;
      };
  servicesSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        services?:
          | T
          | {
              title?: T;
              description?: T;
              iconSvg?: T;
              id?: T;
            };
      };
  showreel?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        videoUrl?: T;
        isComingSoon?: T;
      };
  portfolioGallery?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  processSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        steps?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  pricingSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        note?: T;
        plans?:
          | T
          | {
              name?: T;
              price?: T;
              period?: T;
              description?: T;
              isPopular?: T;
              features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  faqSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        primaryButtonText?: T;
        whatsappButtonText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seoPage_select".
 */
export interface SeoPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        headline?: T;
        subtitle?: T;
        primaryCtaText?: T;
        secondaryCtaText?: T;
        media?: T;
      };
  servicesSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        services?:
          | T
          | {
              title?: T;
              description?: T;
              iconSvg?: T;
              features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  portfolioGallery?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  processSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        steps?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  pricingSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        note?: T;
        plans?:
          | T
          | {
              name?: T;
              price?: T;
              period?: T;
              description?: T;
              isPopular?: T;
              features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  faqSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        primaryButtonText?: T;
        whatsappButtonText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brandStudioPage_select".
 */
export interface BrandStudioPageSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  settings?:
    | T
    | {
        whatsappNumber?: T;
        calendlyUrl?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        headingTop?: T;
        headingAccent?: T;
        subheading?: T;
        primaryCtaText?: T;
        secondaryCtaText?: T;
        trustText?: T;
      };
  howSection?:
    | T
    | {
        heading?: T;
        subheading?: T;
        steps?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  pricingSection?:
    | T
    | {
        heading?: T;
        subheading?: T;
        addonsText?: T;
        unsureText?: T;
        plans?:
          | T
          | {
              name?: T;
              price?: T;
              blurb?: T;
              isPopular?: T;
              ctaText?: T;
              features?:
                | T
                | {
                    feature?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  whySection?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  faqSection?:
    | T
    | {
        heading?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  finalCta?:
    | T
    | {
        heading?: T;
        subheading?: T;
        primaryCtaText?: T;
        whatsappCtaText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}