import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Backfills columns the code expects but no migration ever created: the full
 * `clients` CRM expansion (+ its three enums), the redesigned `contact_page`
 * fields, and the `onboarding_documents` relationship column on
 * `payload_locked_documents_rels`. These were added to the collection/global
 * field configs without a matching migration, so a from-scratch replay was
 * missing them (and production only has them if a dev push reached it).
 *
 * DDL generated by drizzle from the current schema, then made idempotent
 * (CREATE ... IF NOT EXISTS / duplicate_object guards) so it is a no-op wherever
 * the objects already exist and repairs any database that is missing them.
 *
 * Note: the pre-redesign contact_page columns (title/description/heading/
 * subheading) and the `_pages_v`/`_blog_posts_v` autosave columns are left in
 * place on purpose — dropping columns is destructive and is handled separately
 * once production's actual state is confirmed.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  DO $$ BEGIN CREATE TYPE "public"."enum_clients_service" AS ENUM('web-design', 'digital-marketing', 'branding', 'video-production', 'seo-paid-ads', 'social-media', 'multiple'); EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN CREATE TYPE "public"."enum_clients_pipeline_status" AS ENUM('lead', 'discovery', 'proposal', 'negotiating', 'won', 'lost', 'on-hold', 'active', 'completed'); EXCEPTION WHEN duplicate_object THEN null; END $$;
  DO $$ BEGIN CREATE TYPE "public"."enum_clients_source" AS ENUM('website', 'whatsapp', 'referral', 'social', 'walk-in', 'other'); EXCEPTION WHEN duplicate_object THEN null; END $$;

  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "contact_name" varchar;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "client_email" varchar;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "phone" varchar;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "service" "enum_clients_service";
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "package" varchar;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "price" numeric;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "start_date" timestamp(3) with time zone;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "pipeline_status" "enum_clients_pipeline_status" DEFAULT 'lead';
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "source" "enum_clients_source";
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "documents_sent_contract" boolean DEFAULT false;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "documents_sent_invoice" boolean DEFAULT false;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "documents_sent_onboarding_email" boolean DEFAULT false;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "documents_sent_setup_instructions" boolean DEFAULT false;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "proposal_url" varchar;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "notes" varchar;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "customizations_duration" numeric;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "customizations_revisions" numeric;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "customizations_deposit_percent" numeric;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "customizations_number_of_pages" numeric;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "customizations_posts_per_month" numeric;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "customizations_platforms" varchar;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "customizations_payment_terms" varchar;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "customizations_extra_deliverables" varchar;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "customizations_special_terms" varchar;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "email_notes_welcome" varchar;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "email_notes_contract" varchar;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "email_notes_setup" varchar;
  ALTER TABLE "clients" ADD COLUMN IF NOT EXISTS "email_notes_checkin" varchar;

  ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "hero_heading" varchar;
  ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "hero_subtitle" varchar;
  ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "contact_subtitle" varchar;
  ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "contact_text" varchar;
  ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "whatsapp_button_text" varchar;
  ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "whatsapp_message" varchar;
  ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "form_success_message" varchar;
  ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "submit_button_text" varchar;
  ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "booking_divider_text" varchar;
  ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "booking_heading" varchar;
  ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "booking_subtitle" varchar;
  ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "calendly_url" varchar;
  ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "show_booking_section" boolean DEFAULT true;

  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN IF NOT EXISTS "onboarding_documents_id" integer;
  DO $$ BEGIN
    ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_onboarding_documents_fk" FOREIGN KEY ("onboarding_documents_id") REFERENCES "public"."onboarding_documents"("id") ON DELETE cascade ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;
  CREATE INDEX IF NOT EXISTS "payload_locked_documents_rels_onboarding_documents_id_idx" ON "payload_locked_documents_rels" USING btree ("onboarding_documents_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP INDEX IF EXISTS "payload_locked_documents_rels_onboarding_documents_id_idx";
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_onboarding_documents_fk";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN IF EXISTS "onboarding_documents_id";

  ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "hero_heading";
  ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "hero_subtitle";
  ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "contact_subtitle";
  ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "contact_text";
  ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "whatsapp_button_text";
  ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "whatsapp_message";
  ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "form_success_message";
  ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "submit_button_text";
  ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "booking_divider_text";
  ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "booking_heading";
  ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "booking_subtitle";
  ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "calendly_url";
  ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "show_booking_section";

  ALTER TABLE "clients" DROP COLUMN IF EXISTS "contact_name";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "client_email";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "phone";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "service";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "package";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "price";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "start_date";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "pipeline_status";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "source";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "documents_sent_contract";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "documents_sent_invoice";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "documents_sent_onboarding_email";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "documents_sent_setup_instructions";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "proposal_url";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "notes";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "customizations_duration";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "customizations_revisions";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "customizations_deposit_percent";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "customizations_number_of_pages";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "customizations_posts_per_month";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "customizations_platforms";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "customizations_payment_terms";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "customizations_extra_deliverables";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "customizations_special_terms";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "email_notes_welcome";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "email_notes_contract";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "email_notes_setup";
  ALTER TABLE "clients" DROP COLUMN IF EXISTS "email_notes_checkin";

  DROP TYPE IF EXISTS "public"."enum_clients_source";
  DROP TYPE IF EXISTS "public"."enum_clients_pipeline_status";
  DROP TYPE IF EXISTS "public"."enum_clients_service";`)
}
