import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/*
  Electronic signing: documents to sign, one private session per signer, and
  the signed copies. Generated by migrate:create on 2026-10-04, then edited by
  hand in two places, so the .json snapshot differs from this file on purpose:

  1. signing_sessions.request_id is NOT NULL, and the generator gave its foreign
     key ON DELETE SET NULL. Those contradict each other, so deleting a draft
     request would fail as a 500 (see "A required relationship cannot be
     deleted from the parent end" in cms/CLAUDE.md). It is ON DELETE CASCADE
     here: a session means nothing without its request. Requests that have
     been sent cannot be deleted at all; a beforeDelete hook refuses them.

  2. down() drops the three edit-lock constraints with IF EXISTS. The
     DROP TABLE ... CASCADE lines just before them have already removed those
     constraints, so the generated plain DROP CONSTRAINT failed when this was
     rehearsed against production inside a rolled-back transaction.
*/

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_signature_requests_places_kind" AS ENUM('signature', 'initials', 'name', 'date', 'title');
  CREATE TYPE "public"."enum_signature_requests_status" AS ENUM('draft', 'out', 'completing', 'completed', 'declined', 'cancelled', 'expired');
  CREATE TYPE "public"."enum_signing_sessions_status" AS ENUM('waiting', 'sent', 'opened', 'signed', 'declined', 'cancelled');
  ALTER TYPE "public"."enum_payload_jobs_log_task_slug" ADD VALUE 'signingRounds' BEFORE 'schedulePublish';
  ALTER TYPE "public"."enum_payload_jobs_task_slug" ADD VALUE 'signingRounds' BEFORE 'schedulePublish';
  CREATE TABLE "signature_requests_signers" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"name" varchar NOT NULL,
  	"email" varchar NOT NULL,
  	"role" varchar,
  	"organisation" varchar,
  	"title" varchar
  );
  
  CREATE TABLE "signature_requests_parties" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"party_id" varchar NOT NULL,
  	"page" numeric,
  	"witness" boolean,
  	"context" varchar,
  	"signer_id" varchar,
  	"manual" boolean
  );
  
  CREATE TABLE "signature_requests_places" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"page" numeric NOT NULL,
  	"x" numeric NOT NULL,
  	"y" numeric NOT NULL,
  	"width" numeric NOT NULL,
  	"height" numeric NOT NULL,
  	"kind" "enum_signature_requests_places_kind" NOT NULL,
  	"party" varchar NOT NULL,
  	"context" varchar
  );
  
  CREATE TABLE "signature_requests_events" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"at" timestamp(3) with time zone NOT NULL,
  	"text" varchar NOT NULL
  );
  
  CREATE TABLE "signature_requests" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"title" varchar NOT NULL,
  	"message" varchar,
  	"require_code" boolean DEFAULT false,
  	"sign_in_order" boolean DEFAULT false,
  	"expires_in_days" numeric DEFAULT 30,
  	"remind_every_days" numeric DEFAULT 3,
  	"client_id" integer,
  	"member_id" integer,
  	"status" "enum_signature_requests_status" DEFAULT 'draft',
  	"reference" varchar,
  	"sent_at" timestamp(3) with time zone,
  	"expires_at" timestamp(3) with time zone,
  	"completed_at" timestamp(3) with time zone,
  	"sent_by_id" integer,
  	"original_hash" varchar,
  	"signed_hash" varchar,
  	"signed_file_id" integer,
  	"pages" jsonb,
  	"prefix" varchar DEFAULT 'signing',
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"url" varchar,
  	"thumbnail_u_r_l" varchar,
  	"filename" varchar,
  	"mime_type" varchar,
  	"filesize" numeric,
  	"width" numeric,
  	"height" numeric,
  	"focal_x" numeric,
  	"focal_y" numeric
  );
  
  CREATE TABLE "signing_sessions_events" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"at" timestamp(3) with time zone NOT NULL,
  	"text" varchar NOT NULL
  );
  
  CREATE TABLE "signing_sessions" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"request_id" integer NOT NULL,
  	"signer_id" varchar NOT NULL,
  	"order" numeric DEFAULT 0,
  	"name" varchar NOT NULL,
  	"email" varchar NOT NULL,
  	"role" varchar,
  	"organisation" varchar,
  	"title" varchar,
  	"status" "enum_signing_sessions_status" DEFAULT 'sent',
  	"token_hash" varchar NOT NULL,
  	"token_sealed" varchar,
  	"sent_at" timestamp(3) with time zone,
  	"opened_at" timestamp(3) with time zone,
  	"signed_at" timestamp(3) with time zone,
  	"declined_at" timestamp(3) with time zone,
  	"decline_reason" varchar,
  	"ip" varchar,
  	"device" varchar,
  	"code_hash" varchar,
  	"code_sent_at" timestamp(3) with time zone,
  	"codes_sent" numeric DEFAULT 0,
  	"code_tries" numeric DEFAULT 0,
  	"code_verified" boolean DEFAULT false,
  	"reminded_at" timestamp(3) with time zone,
  	"reminders" numeric DEFAULT 0,
  	"signature" varchar,
  	"initials" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "signed_documents" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"title" varchar,
  	"reference" varchar,
  	"request_id" integer,
  	"hash" varchar,
  	"prefix" varchar DEFAULT 'signed',
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"url" varchar,
  	"thumbnail_u_r_l" varchar,
  	"filename" varchar,
  	"mime_type" varchar,
  	"filesize" numeric,
  	"width" numeric,
  	"height" numeric,
  	"focal_x" numeric,
  	"focal_y" numeric
  );
  
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "signature_requests_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "signing_sessions_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "signed_documents_id" integer;
  ALTER TABLE "signature_requests_signers" ADD CONSTRAINT "signature_requests_signers_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."signature_requests"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "signature_requests_parties" ADD CONSTRAINT "signature_requests_parties_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."signature_requests"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "signature_requests_places" ADD CONSTRAINT "signature_requests_places_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."signature_requests"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "signature_requests_events" ADD CONSTRAINT "signature_requests_events_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."signature_requests"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "signature_requests" ADD CONSTRAINT "signature_requests_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "signature_requests" ADD CONSTRAINT "signature_requests_member_id_users_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "signature_requests" ADD CONSTRAINT "signature_requests_sent_by_id_users_id_fk" FOREIGN KEY ("sent_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "signature_requests" ADD CONSTRAINT "signature_requests_signed_file_id_signed_documents_id_fk" FOREIGN KEY ("signed_file_id") REFERENCES "public"."signed_documents"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "signing_sessions_events" ADD CONSTRAINT "signing_sessions_events_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."signing_sessions"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "signing_sessions" ADD CONSTRAINT "signing_sessions_request_id_signature_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."signature_requests"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "signed_documents" ADD CONSTRAINT "signed_documents_request_id_signature_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."signature_requests"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "signature_requests_signers_order_idx" ON "signature_requests_signers" USING btree ("_order");
  CREATE INDEX "signature_requests_signers_parent_id_idx" ON "signature_requests_signers" USING btree ("_parent_id");
  CREATE INDEX "signature_requests_parties_order_idx" ON "signature_requests_parties" USING btree ("_order");
  CREATE INDEX "signature_requests_parties_parent_id_idx" ON "signature_requests_parties" USING btree ("_parent_id");
  CREATE INDEX "signature_requests_places_order_idx" ON "signature_requests_places" USING btree ("_order");
  CREATE INDEX "signature_requests_places_parent_id_idx" ON "signature_requests_places" USING btree ("_parent_id");
  CREATE INDEX "signature_requests_events_order_idx" ON "signature_requests_events" USING btree ("_order");
  CREATE INDEX "signature_requests_events_parent_id_idx" ON "signature_requests_events" USING btree ("_parent_id");
  CREATE INDEX "signature_requests_client_idx" ON "signature_requests" USING btree ("client_id");
  CREATE INDEX "signature_requests_member_idx" ON "signature_requests" USING btree ("member_id");
  CREATE INDEX "signature_requests_status_idx" ON "signature_requests" USING btree ("status");
  CREATE INDEX "signature_requests_sent_by_idx" ON "signature_requests" USING btree ("sent_by_id");
  CREATE INDEX "signature_requests_signed_file_idx" ON "signature_requests" USING btree ("signed_file_id");
  CREATE INDEX "signature_requests_updated_at_idx" ON "signature_requests" USING btree ("updated_at");
  CREATE INDEX "signature_requests_created_at_idx" ON "signature_requests" USING btree ("created_at");
  CREATE UNIQUE INDEX "signature_requests_filename_idx" ON "signature_requests" USING btree ("filename");
  CREATE INDEX "signing_sessions_events_order_idx" ON "signing_sessions_events" USING btree ("_order");
  CREATE INDEX "signing_sessions_events_parent_id_idx" ON "signing_sessions_events" USING btree ("_parent_id");
  CREATE INDEX "signing_sessions_request_idx" ON "signing_sessions" USING btree ("request_id");
  CREATE INDEX "signing_sessions_signer_id_idx" ON "signing_sessions" USING btree ("signer_id");
  CREATE INDEX "signing_sessions_status_idx" ON "signing_sessions" USING btree ("status");
  CREATE UNIQUE INDEX "signing_sessions_token_hash_idx" ON "signing_sessions" USING btree ("token_hash");
  CREATE INDEX "signing_sessions_updated_at_idx" ON "signing_sessions" USING btree ("updated_at");
  CREATE INDEX "signing_sessions_created_at_idx" ON "signing_sessions" USING btree ("created_at");
  CREATE INDEX "signed_documents_request_idx" ON "signed_documents" USING btree ("request_id");
  CREATE INDEX "signed_documents_updated_at_idx" ON "signed_documents" USING btree ("updated_at");
  CREATE INDEX "signed_documents_created_at_idx" ON "signed_documents" USING btree ("created_at");
  CREATE UNIQUE INDEX "signed_documents_filename_idx" ON "signed_documents" USING btree ("filename");
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_signature_requests_fk" FOREIGN KEY ("signature_requests_id") REFERENCES "public"."signature_requests"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_signing_sessions_fk" FOREIGN KEY ("signing_sessions_id") REFERENCES "public"."signing_sessions"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_signed_documents_fk" FOREIGN KEY ("signed_documents_id") REFERENCES "public"."signed_documents"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "payload_locked_documents_rels_signature_requests_id_idx" ON "payload_locked_documents_rels" USING btree ("signature_requests_id");
  CREATE INDEX "payload_locked_documents_rels_signing_sessions_id_idx" ON "payload_locked_documents_rels" USING btree ("signing_sessions_id");
  CREATE INDEX "payload_locked_documents_rels_signed_documents_id_idx" ON "payload_locked_documents_rels" USING btree ("signed_documents_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "signature_requests_signers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "signature_requests_parties" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "signature_requests_places" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "signature_requests_events" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "signature_requests" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "signing_sessions_events" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "signing_sessions" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "signed_documents" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "signature_requests_signers" CASCADE;
  DROP TABLE "signature_requests_parties" CASCADE;
  DROP TABLE "signature_requests_places" CASCADE;
  DROP TABLE "signature_requests_events" CASCADE;
  DROP TABLE "signature_requests" CASCADE;
  DROP TABLE "signing_sessions_events" CASCADE;
  DROP TABLE "signing_sessions" CASCADE;
  DROP TABLE "signed_documents" CASCADE;
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_signature_requests_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_signing_sessions_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_signed_documents_fk";
  
  ALTER TABLE "payload_jobs_log" ALTER COLUMN "task_slug" SET DATA TYPE text;
  DROP TYPE "public"."enum_payload_jobs_log_task_slug";
  CREATE TYPE "public"."enum_payload_jobs_log_task_slug" AS ENUM('inline', 'clientOnboarding', 'teamReminders', 'recordInvoicePayment', 'schedulePublish');
  ALTER TABLE "payload_jobs_log" ALTER COLUMN "task_slug" SET DATA TYPE "public"."enum_payload_jobs_log_task_slug" USING "task_slug"::"public"."enum_payload_jobs_log_task_slug";
  ALTER TABLE "payload_jobs" ALTER COLUMN "task_slug" SET DATA TYPE text;
  DROP TYPE "public"."enum_payload_jobs_task_slug";
  CREATE TYPE "public"."enum_payload_jobs_task_slug" AS ENUM('inline', 'clientOnboarding', 'teamReminders', 'recordInvoicePayment', 'schedulePublish');
  ALTER TABLE "payload_jobs" ALTER COLUMN "task_slug" SET DATA TYPE "public"."enum_payload_jobs_task_slug" USING "task_slug"::"public"."enum_payload_jobs_task_slug";
  DROP INDEX "payload_locked_documents_rels_signature_requests_id_idx";
  DROP INDEX "payload_locked_documents_rels_signing_sessions_id_idx";
  DROP INDEX "payload_locked_documents_rels_signed_documents_id_idx";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "signature_requests_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "signing_sessions_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "signed_documents_id";
  DROP TYPE "public"."enum_signature_requests_places_kind";
  DROP TYPE "public"."enum_signature_requests_status";
  DROP TYPE "public"."enum_signing_sessions_status";`)
}
