import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Adds the `onboarding_documents` upload collection's table + its enum. Both
 * exist in the code (collection slug `onboarding-documents`) and in production,
 * but no migration ever created them — so a from-scratch replay was missing the
 * table entirely. Written idempotently (CREATE ... IF NOT EXISTS / duplicate_object
 * guards) so it is a no-op wherever the objects already exist (production) and
 * builds them cleanly on a fresh database.
 *
 * DDL generated by drizzle from the current schema, then made idempotent.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  DO $$ BEGIN
    CREATE TYPE "public"."enum_onboarding_documents_document_type" AS ENUM('sla', 'guide', 'setup', 'combined', 'other');
  EXCEPTION WHEN duplicate_object THEN null; END $$;

  CREATE TABLE IF NOT EXISTS "onboarding_documents" (
    "id" serial PRIMARY KEY NOT NULL,
    "client_id" integer NOT NULL,
    "document_type" "enum_onboarding_documents_document_type" NOT NULL,
    "email_draft_generated" boolean DEFAULT false,
    "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
    "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
    "url" varchar,
    "thumbnail_u_r_l" varchar,
    "filename" varchar,
    "mime_type" varchar,
    "filesize" numeric,
    "width" numeric,
    "height" numeric,
    "focal_x" numeric,
    "focal_y" numeric
  );

  DO $$ BEGIN
    ALTER TABLE "onboarding_documents" ADD CONSTRAINT "onboarding_documents_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE set null ON UPDATE no action;
  EXCEPTION WHEN duplicate_object THEN null; END $$;

  CREATE INDEX IF NOT EXISTS "onboarding_documents_client_idx" ON "onboarding_documents" USING btree ("client_id");
  CREATE INDEX IF NOT EXISTS "onboarding_documents_updated_at_idx" ON "onboarding_documents" USING btree ("updated_at");
  CREATE INDEX IF NOT EXISTS "onboarding_documents_created_at_idx" ON "onboarding_documents" USING btree ("created_at");
  CREATE UNIQUE INDEX IF NOT EXISTS "onboarding_documents_filename_idx" ON "onboarding_documents" USING btree ("filename");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE IF EXISTS "onboarding_documents" CASCADE;
  DROP TYPE IF EXISTS "public"."enum_onboarding_documents_document_type";`)
}
