import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/*
  Before and after measurements on a case study.

  CaseStudies had one resultMetric and one resultText, which can say "300%
  increase in traffic" and cannot say "19.3 seconds became 3.5 seconds". A
  performance case study is a comparison or it is nothing, and this is a
  repeatable product rather than a one-off, so it gets a schema rather than a
  table typed into the body field.

  Generated by `pnpm migrate:create add_case_study_metrics` and then wrapped in
  IF NOT EXISTS / EXCEPTION WHEN duplicate_object, per cms/CLAUDE.md: Railway
  replays migrations on boot and the raw generated form errors on an object
  that already exists.

  One detail worth not getting wrong: an array table's primary key is `varchar`,
  not `serial`. Payload writes a 24 character hex id into it. On a serial
  integer column every array row is silently rejected and the block renders
  empty with nothing in any log to explain it. Confirmed against
  case_studies_image_gallery in the initial baseline.
*/

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS "case_studies_metrics" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" varchar PRIMARY KEY NOT NULL,
      "section" varchar,
      "label" varchar NOT NULL,
      "before" varchar,
      "after" varchar,
      "highlight" boolean DEFAULT false
    );
  `)

  await db.execute(sql`
    ALTER TABLE "case_studies" ADD COLUMN IF NOT EXISTS "metrics_title" varchar;
    ALTER TABLE "case_studies" ADD COLUMN IF NOT EXISTS "metrics_before_label" varchar;
    ALTER TABLE "case_studies" ADD COLUMN IF NOT EXISTS "metrics_after_label" varchar;
    ALTER TABLE "case_studies" ADD COLUMN IF NOT EXISTS "metrics_source" varchar;
  `)

  await db.execute(sql`
    DO $$ BEGIN
      ALTER TABLE "case_studies_metrics" ADD CONSTRAINT "case_studies_metrics_parent_id_fk"
        FOREIGN KEY ("_parent_id") REFERENCES "public"."case_studies"("id")
        ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
  `)

  await db.execute(sql`
    CREATE INDEX IF NOT EXISTS "case_studies_metrics_order_idx" ON "case_studies_metrics" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "case_studies_metrics_parent_id_idx" ON "case_studies_metrics" USING btree ("_parent_id");
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
    DROP TABLE IF EXISTS "case_studies_metrics" CASCADE;
    ALTER TABLE "case_studies" DROP COLUMN IF EXISTS "metrics_title";
    ALTER TABLE "case_studies" DROP COLUMN IF EXISTS "metrics_before_label";
    ALTER TABLE "case_studies" DROP COLUMN IF EXISTS "metrics_after_label";
    ALTER TABLE "case_studies" DROP COLUMN IF EXISTS "metrics_source";
  `)
}
