import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_leads_activity_type" AS ENUM('first-message', 'follow-up', 'reply', 'call', 'proposal-sent', 'other');
  CREATE TYPE "public"."enum_leads_activity_direction" AS ENUM('out', 'in');
  CREATE TYPE "public"."enum_leads_niche" AS ENUM('food', 'beauty', 'health', 'fashion', 'real-estate', 'events', 'fitness', 'other');
  CREATE TYPE "public"."enum_leads_qualification" AS ENUM('no-website', 'domain-dead', 'parked', 'error-page', 'social-only');
  CREATE TYPE "public"."enum__leads_v_version_activity_type" AS ENUM('first-message', 'follow-up', 'reply', 'call', 'proposal-sent', 'other');
  CREATE TYPE "public"."enum__leads_v_version_activity_direction" AS ENUM('out', 'in');
  CREATE TYPE "public"."enum__leads_v_version_niche" AS ENUM('food', 'beauty', 'health', 'fashion', 'real-estate', 'events', 'fitness', 'other');
  CREATE TYPE "public"."enum__leads_v_version_qualification" AS ENUM('no-website', 'domain-dead', 'parked', 'error-page', 'social-only');
  ALTER TYPE "public"."enum_leads_activity_kind" ADD VALUE 'instagram';
  ALTER TYPE "public"."enum_leads_activity_kind" ADD VALUE 'facebook';
  ALTER TYPE "public"."enum_leads_activity_kind" ADD VALUE 'sms';
  ALTER TYPE "public"."enum_leads_source" ADD VALUE 'outreach' BEFORE 'other';
  ALTER TYPE "public"."enum_leads_source" ADD VALUE 'daily-briefing' BEFORE 'other';
  ALTER TYPE "public"."enum_leads_source" ADD VALUE 'referral' BEFORE 'other';
  ALTER TYPE "public"."enum_leads_status" ADD VALUE 'replied' BEFORE 'qualified';
  ALTER TYPE "public"."enum_leads_status" ADD VALUE 'in-conversation' BEFORE 'qualified';
  ALTER TYPE "public"."enum_leads_status" ADD VALUE 'proposal-requested' BEFORE 'qualified';
  ALTER TYPE "public"."enum_leads_status" ADD VALUE 'proposal-sent' BEFORE 'qualified';
  ALTER TYPE "public"."enum_leads_status" ADD VALUE 'no-response' BEFORE 'qualified';
  ALTER TYPE "public"."enum__leads_v_version_activity_kind" ADD VALUE 'instagram';
  ALTER TYPE "public"."enum__leads_v_version_activity_kind" ADD VALUE 'facebook';
  ALTER TYPE "public"."enum__leads_v_version_activity_kind" ADD VALUE 'sms';
  ALTER TYPE "public"."enum__leads_v_version_source" ADD VALUE 'outreach' BEFORE 'other';
  ALTER TYPE "public"."enum__leads_v_version_source" ADD VALUE 'daily-briefing' BEFORE 'other';
  ALTER TYPE "public"."enum__leads_v_version_source" ADD VALUE 'referral' BEFORE 'other';
  ALTER TYPE "public"."enum__leads_v_version_status" ADD VALUE 'replied' BEFORE 'qualified';
  ALTER TYPE "public"."enum__leads_v_version_status" ADD VALUE 'in-conversation' BEFORE 'qualified';
  ALTER TYPE "public"."enum__leads_v_version_status" ADD VALUE 'proposal-requested' BEFORE 'qualified';
  ALTER TYPE "public"."enum__leads_v_version_status" ADD VALUE 'proposal-sent' BEFORE 'qualified';
  ALTER TYPE "public"."enum__leads_v_version_status" ADD VALUE 'no-response' BEFORE 'qualified';
  ALTER TABLE "leads" ALTER COLUMN "name" DROP NOT NULL;
  ALTER TABLE "leads" ALTER COLUMN "email" DROP NOT NULL;
  ALTER TABLE "_leads_v" ALTER COLUMN "version_name" DROP NOT NULL;
  ALTER TABLE "_leads_v" ALTER COLUMN "version_email" DROP NOT NULL;
  ALTER TABLE "leads_activity" ADD COLUMN "type" "enum_leads_activity_type";
  ALTER TABLE "leads_activity" ADD COLUMN "direction" "enum_leads_activity_direction";
  ALTER TABLE "leads_activity" ADD COLUMN "by_id" integer;
  ALTER TABLE "leads_activity" ADD COLUMN "recorded_at" timestamp(3) with time zone;
  ALTER TABLE "leads" ADD COLUMN "title" varchar;
  ALTER TABLE "leads" ADD COLUMN "business_name" varchar;
  ALTER TABLE "leads" ADD COLUMN "phone" varchar;
  ALTER TABLE "leads" ADD COLUMN "whatsapp" varchar;
  ALTER TABLE "leads" ADD COLUMN "website" varchar;
  ALTER TABLE "leads" ADD COLUMN "found_at" varchar;
  ALTER TABLE "leads" ADD COLUMN "niche" "enum_leads_niche";
  ALTER TABLE "leads" ADD COLUMN "city" varchar;
  ALTER TABLE "leads" ADD COLUMN "country" varchar;
  ALTER TABLE "leads" ADD COLUMN "qualification" "enum_leads_qualification";
  ALTER TABLE "leads" ADD COLUMN "owner_id" integer;
  ALTER TABLE "leads" ADD COLUMN "owner_change_reason" varchar;
  ALTER TABLE "leads" ADD COLUMN "logged_at" timestamp(3) with time zone;
  ALTER TABLE "leads" ADD COLUMN "assigned_to_id" integer;
  ALTER TABLE "leads" ADD COLUMN "assigned_at" timestamp(3) with time zone;
  ALTER TABLE "leads" ADD COLUMN "first_contacted_at" timestamp(3) with time zone;
  ALTER TABLE "leads" ADD COLUMN "last_contact_at" timestamp(3) with time zone;
  ALTER TABLE "leads" ADD COLUMN "follow_up_count" numeric;
  ALTER TABLE "leads" ADD COLUMN "phone_key" varchar;
  ALTER TABLE "leads" ADD COLUMN "whatsapp_key" varchar;
  ALTER TABLE "leads" ADD COLUMN "website_key" varchar;
  ALTER TABLE "leads" ADD COLUMN "name_city_key" varchar;
  ALTER TABLE "_leads_v_version_activity" ADD COLUMN "type" "enum__leads_v_version_activity_type";
  ALTER TABLE "_leads_v_version_activity" ADD COLUMN "direction" "enum__leads_v_version_activity_direction";
  ALTER TABLE "_leads_v_version_activity" ADD COLUMN "by_id" integer;
  ALTER TABLE "_leads_v_version_activity" ADD COLUMN "recorded_at" timestamp(3) with time zone;
  ALTER TABLE "_leads_v" ADD COLUMN "version_title" varchar;
  ALTER TABLE "_leads_v" ADD COLUMN "version_business_name" varchar;
  ALTER TABLE "_leads_v" ADD COLUMN "version_phone" varchar;
  ALTER TABLE "_leads_v" ADD COLUMN "version_whatsapp" varchar;
  ALTER TABLE "_leads_v" ADD COLUMN "version_website" varchar;
  ALTER TABLE "_leads_v" ADD COLUMN "version_found_at" varchar;
  ALTER TABLE "_leads_v" ADD COLUMN "version_niche" "enum__leads_v_version_niche";
  ALTER TABLE "_leads_v" ADD COLUMN "version_city" varchar;
  ALTER TABLE "_leads_v" ADD COLUMN "version_country" varchar;
  ALTER TABLE "_leads_v" ADD COLUMN "version_qualification" "enum__leads_v_version_qualification";
  ALTER TABLE "_leads_v" ADD COLUMN "version_owner_id" integer;
  ALTER TABLE "_leads_v" ADD COLUMN "version_owner_change_reason" varchar;
  ALTER TABLE "_leads_v" ADD COLUMN "version_logged_at" timestamp(3) with time zone;
  ALTER TABLE "_leads_v" ADD COLUMN "version_assigned_to_id" integer;
  ALTER TABLE "_leads_v" ADD COLUMN "version_assigned_at" timestamp(3) with time zone;
  ALTER TABLE "_leads_v" ADD COLUMN "version_first_contacted_at" timestamp(3) with time zone;
  ALTER TABLE "_leads_v" ADD COLUMN "version_last_contact_at" timestamp(3) with time zone;
  ALTER TABLE "_leads_v" ADD COLUMN "version_follow_up_count" numeric;
  ALTER TABLE "_leads_v" ADD COLUMN "version_phone_key" varchar;
  ALTER TABLE "_leads_v" ADD COLUMN "version_whatsapp_key" varchar;
  ALTER TABLE "_leads_v" ADD COLUMN "version_website_key" varchar;
  ALTER TABLE "_leads_v" ADD COLUMN "version_name_city_key" varchar;
  ALTER TABLE "pitches" ADD COLUMN "lead_id" integer;
  ALTER TABLE "leads_activity" ADD CONSTRAINT "leads_activity_by_id_users_id_fk" FOREIGN KEY ("by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "leads" ADD CONSTRAINT "leads_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "leads" ADD CONSTRAINT "leads_assigned_to_id_users_id_fk" FOREIGN KEY ("assigned_to_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_leads_v_version_activity" ADD CONSTRAINT "_leads_v_version_activity_by_id_users_id_fk" FOREIGN KEY ("by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_leads_v" ADD CONSTRAINT "_leads_v_version_owner_id_users_id_fk" FOREIGN KEY ("version_owner_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_leads_v" ADD CONSTRAINT "_leads_v_version_assigned_to_id_users_id_fk" FOREIGN KEY ("version_assigned_to_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pitches" ADD CONSTRAINT "pitches_lead_id_leads_id_fk" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "leads_activity_by_idx" ON "leads_activity" USING btree ("by_id");
  CREATE INDEX "leads_owner_idx" ON "leads" USING btree ("owner_id");
  CREATE INDEX "leads_logged_at_idx" ON "leads" USING btree ("logged_at");
  CREATE INDEX "leads_assigned_to_idx" ON "leads" USING btree ("assigned_to_id");
  CREATE INDEX "leads_phone_key_idx" ON "leads" USING btree ("phone_key");
  CREATE INDEX "leads_whatsapp_key_idx" ON "leads" USING btree ("whatsapp_key");
  CREATE INDEX "leads_website_key_idx" ON "leads" USING btree ("website_key");
  CREATE INDEX "leads_name_city_key_idx" ON "leads" USING btree ("name_city_key");
  CREATE INDEX "_leads_v_version_activity_by_idx" ON "_leads_v_version_activity" USING btree ("by_id");
  CREATE INDEX "_leads_v_version_version_owner_idx" ON "_leads_v" USING btree ("version_owner_id");
  CREATE INDEX "_leads_v_version_version_logged_at_idx" ON "_leads_v" USING btree ("version_logged_at");
  CREATE INDEX "_leads_v_version_version_assigned_to_idx" ON "_leads_v" USING btree ("version_assigned_to_id");
  CREATE INDEX "_leads_v_version_version_phone_key_idx" ON "_leads_v" USING btree ("version_phone_key");
  CREATE INDEX "_leads_v_version_version_whatsapp_key_idx" ON "_leads_v" USING btree ("version_whatsapp_key");
  CREATE INDEX "_leads_v_version_version_website_key_idx" ON "_leads_v" USING btree ("version_website_key");
  CREATE INDEX "_leads_v_version_version_name_city_key_idx" ON "_leads_v" USING btree ("version_name_city_key");
  CREATE INDEX "pitches_lead_idx" ON "pitches" USING btree ("lead_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "leads_activity" DROP CONSTRAINT "leads_activity_by_id_users_id_fk";
  
  ALTER TABLE "leads" DROP CONSTRAINT "leads_owner_id_users_id_fk";
  
  ALTER TABLE "leads" DROP CONSTRAINT "leads_assigned_to_id_users_id_fk";
  
  ALTER TABLE "_leads_v_version_activity" DROP CONSTRAINT "_leads_v_version_activity_by_id_users_id_fk";
  
  ALTER TABLE "_leads_v" DROP CONSTRAINT "_leads_v_version_owner_id_users_id_fk";
  
  ALTER TABLE "_leads_v" DROP CONSTRAINT "_leads_v_version_assigned_to_id_users_id_fk";
  
  ALTER TABLE "pitches" DROP CONSTRAINT "pitches_lead_id_leads_id_fk";
  
  ALTER TABLE "leads_activity" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "leads_activity" ALTER COLUMN "kind" SET DEFAULT 'whatsapp'::text;
  DROP TYPE "public"."enum_leads_activity_kind";
  CREATE TYPE "public"."enum_leads_activity_kind" AS ENUM('whatsapp', 'call', 'email', 'meeting', 'note');
  ALTER TABLE "leads_activity" ALTER COLUMN "kind" SET DEFAULT 'whatsapp'::"public"."enum_leads_activity_kind";
  ALTER TABLE "leads_activity" ALTER COLUMN "kind" SET DATA TYPE "public"."enum_leads_activity_kind" USING "kind"::"public"."enum_leads_activity_kind";
  ALTER TABLE "leads" ALTER COLUMN "source" SET DATA TYPE text;
  DROP TYPE "public"."enum_leads_source";
  CREATE TYPE "public"."enum_leads_source" AS ENUM('contact-form', 'homepage', 'cms-page', 'brand-studio', 'lead-magnet', 'newsletter', 'calculator', 'whatsapp', 'other');
  ALTER TABLE "leads" ALTER COLUMN "source" SET DATA TYPE "public"."enum_leads_source" USING "source"::"public"."enum_leads_source";
  ALTER TABLE "leads" ALTER COLUMN "status" SET DATA TYPE text;
  ALTER TABLE "leads" ALTER COLUMN "status" SET DEFAULT 'new'::text;
  DROP TYPE "public"."enum_leads_status";
  CREATE TYPE "public"."enum_leads_status" AS ENUM('new', 'contacted', 'qualified', 'won', 'lost', 'archived');
  ALTER TABLE "leads" ALTER COLUMN "status" SET DEFAULT 'new'::"public"."enum_leads_status";
  ALTER TABLE "leads" ALTER COLUMN "status" SET DATA TYPE "public"."enum_leads_status" USING "status"::"public"."enum_leads_status";
  ALTER TABLE "_leads_v_version_activity" ALTER COLUMN "kind" SET DATA TYPE text;
  ALTER TABLE "_leads_v_version_activity" ALTER COLUMN "kind" SET DEFAULT 'whatsapp'::text;
  DROP TYPE "public"."enum__leads_v_version_activity_kind";
  CREATE TYPE "public"."enum__leads_v_version_activity_kind" AS ENUM('whatsapp', 'call', 'email', 'meeting', 'note');
  ALTER TABLE "_leads_v_version_activity" ALTER COLUMN "kind" SET DEFAULT 'whatsapp'::"public"."enum__leads_v_version_activity_kind";
  ALTER TABLE "_leads_v_version_activity" ALTER COLUMN "kind" SET DATA TYPE "public"."enum__leads_v_version_activity_kind" USING "kind"::"public"."enum__leads_v_version_activity_kind";
  ALTER TABLE "_leads_v" ALTER COLUMN "version_source" SET DATA TYPE text;
  DROP TYPE "public"."enum__leads_v_version_source";
  CREATE TYPE "public"."enum__leads_v_version_source" AS ENUM('contact-form', 'homepage', 'cms-page', 'brand-studio', 'lead-magnet', 'newsletter', 'calculator', 'whatsapp', 'other');
  ALTER TABLE "_leads_v" ALTER COLUMN "version_source" SET DATA TYPE "public"."enum__leads_v_version_source" USING "version_source"::"public"."enum__leads_v_version_source";
  ALTER TABLE "_leads_v" ALTER COLUMN "version_status" SET DATA TYPE text;
  ALTER TABLE "_leads_v" ALTER COLUMN "version_status" SET DEFAULT 'new'::text;
  DROP TYPE "public"."enum__leads_v_version_status";
  CREATE TYPE "public"."enum__leads_v_version_status" AS ENUM('new', 'contacted', 'qualified', 'won', 'lost', 'archived');
  ALTER TABLE "_leads_v" ALTER COLUMN "version_status" SET DEFAULT 'new'::"public"."enum__leads_v_version_status";
  ALTER TABLE "_leads_v" ALTER COLUMN "version_status" SET DATA TYPE "public"."enum__leads_v_version_status" USING "version_status"::"public"."enum__leads_v_version_status";
  DROP INDEX "leads_activity_by_idx";
  DROP INDEX "leads_owner_idx";
  DROP INDEX "leads_logged_at_idx";
  DROP INDEX "leads_assigned_to_idx";
  DROP INDEX "leads_phone_key_idx";
  DROP INDEX "leads_whatsapp_key_idx";
  DROP INDEX "leads_website_key_idx";
  DROP INDEX "leads_name_city_key_idx";
  DROP INDEX "_leads_v_version_activity_by_idx";
  DROP INDEX "_leads_v_version_version_owner_idx";
  DROP INDEX "_leads_v_version_version_logged_at_idx";
  DROP INDEX "_leads_v_version_version_assigned_to_idx";
  DROP INDEX "_leads_v_version_version_phone_key_idx";
  DROP INDEX "_leads_v_version_version_whatsapp_key_idx";
  DROP INDEX "_leads_v_version_version_website_key_idx";
  DROP INDEX "_leads_v_version_version_name_city_key_idx";
  DROP INDEX "pitches_lead_idx";
  ALTER TABLE "leads" ALTER COLUMN "name" SET NOT NULL;
  ALTER TABLE "leads" ALTER COLUMN "email" SET NOT NULL;
  ALTER TABLE "_leads_v" ALTER COLUMN "version_name" SET NOT NULL;
  ALTER TABLE "_leads_v" ALTER COLUMN "version_email" SET NOT NULL;
  ALTER TABLE "leads_activity" DROP COLUMN "type";
  ALTER TABLE "leads_activity" DROP COLUMN "direction";
  ALTER TABLE "leads_activity" DROP COLUMN "by_id";
  ALTER TABLE "leads_activity" DROP COLUMN "recorded_at";
  ALTER TABLE "leads" DROP COLUMN "title";
  ALTER TABLE "leads" DROP COLUMN "business_name";
  ALTER TABLE "leads" DROP COLUMN "phone";
  ALTER TABLE "leads" DROP COLUMN "whatsapp";
  ALTER TABLE "leads" DROP COLUMN "website";
  ALTER TABLE "leads" DROP COLUMN "found_at";
  ALTER TABLE "leads" DROP COLUMN "niche";
  ALTER TABLE "leads" DROP COLUMN "city";
  ALTER TABLE "leads" DROP COLUMN "country";
  ALTER TABLE "leads" DROP COLUMN "qualification";
  ALTER TABLE "leads" DROP COLUMN "owner_id";
  ALTER TABLE "leads" DROP COLUMN "owner_change_reason";
  ALTER TABLE "leads" DROP COLUMN "logged_at";
  ALTER TABLE "leads" DROP COLUMN "assigned_to_id";
  ALTER TABLE "leads" DROP COLUMN "assigned_at";
  ALTER TABLE "leads" DROP COLUMN "first_contacted_at";
  ALTER TABLE "leads" DROP COLUMN "last_contact_at";
  ALTER TABLE "leads" DROP COLUMN "follow_up_count";
  ALTER TABLE "leads" DROP COLUMN "phone_key";
  ALTER TABLE "leads" DROP COLUMN "whatsapp_key";
  ALTER TABLE "leads" DROP COLUMN "website_key";
  ALTER TABLE "leads" DROP COLUMN "name_city_key";
  ALTER TABLE "_leads_v_version_activity" DROP COLUMN "type";
  ALTER TABLE "_leads_v_version_activity" DROP COLUMN "direction";
  ALTER TABLE "_leads_v_version_activity" DROP COLUMN "by_id";
  ALTER TABLE "_leads_v_version_activity" DROP COLUMN "recorded_at";
  ALTER TABLE "_leads_v" DROP COLUMN "version_title";
  ALTER TABLE "_leads_v" DROP COLUMN "version_business_name";
  ALTER TABLE "_leads_v" DROP COLUMN "version_phone";
  ALTER TABLE "_leads_v" DROP COLUMN "version_whatsapp";
  ALTER TABLE "_leads_v" DROP COLUMN "version_website";
  ALTER TABLE "_leads_v" DROP COLUMN "version_found_at";
  ALTER TABLE "_leads_v" DROP COLUMN "version_niche";
  ALTER TABLE "_leads_v" DROP COLUMN "version_city";
  ALTER TABLE "_leads_v" DROP COLUMN "version_country";
  ALTER TABLE "_leads_v" DROP COLUMN "version_qualification";
  ALTER TABLE "_leads_v" DROP COLUMN "version_owner_id";
  ALTER TABLE "_leads_v" DROP COLUMN "version_owner_change_reason";
  ALTER TABLE "_leads_v" DROP COLUMN "version_logged_at";
  ALTER TABLE "_leads_v" DROP COLUMN "version_assigned_to_id";
  ALTER TABLE "_leads_v" DROP COLUMN "version_assigned_at";
  ALTER TABLE "_leads_v" DROP COLUMN "version_first_contacted_at";
  ALTER TABLE "_leads_v" DROP COLUMN "version_last_contact_at";
  ALTER TABLE "_leads_v" DROP COLUMN "version_follow_up_count";
  ALTER TABLE "_leads_v" DROP COLUMN "version_phone_key";
  ALTER TABLE "_leads_v" DROP COLUMN "version_whatsapp_key";
  ALTER TABLE "_leads_v" DROP COLUMN "version_website_key";
  ALTER TABLE "_leads_v" DROP COLUMN "version_name_city_key";
  ALTER TABLE "pitches" DROP COLUMN "lead_id";
  DROP TYPE "public"."enum_leads_activity_type";
  DROP TYPE "public"."enum_leads_activity_direction";
  DROP TYPE "public"."enum_leads_niche";
  DROP TYPE "public"."enum_leads_qualification";
  DROP TYPE "public"."enum__leads_v_version_activity_type";
  DROP TYPE "public"."enum__leads_v_version_activity_direction";
  DROP TYPE "public"."enum__leads_v_version_niche";
  DROP TYPE "public"."enum__leads_v_version_qualification";`)
}
