import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Three changes, all from the same schema diff.
 *
 * 1. Revision history on Leads, Clients and Invoices. `versions` without
 *    `drafts`, so saving still takes effect immediately and there is no draft
 *    state, but every save is recorded and can be restored. Each collection
 *    gets a `_<slug>_v` table mirroring its fields, plus a child table per
 *    array field.
 *
 * 2. The jobs queue (`payload_jobs`, `payload_jobs_log`), which exists so that
 *    scheduled publishing on Blog Posts and Pages has somewhere to put the
 *    job and something to run it. See the `jobs` block in payload.config.ts.
 *
 * 3. Twenty-one column defaults on four page globals that had drifted. These
 *    are unrelated to the above and are here because the diff surfaced them:
 *    production still carries the pre-rename Video Production wording and the
 *    em dashes that were removed from the code earlier today. Column defaults
 *    almost never surface, because Payload applies `defaultValue` in JS before
 *    the insert, but leaving them stale would have baked the drift into the
 *    snapshot this migration writes.
 *
 * Generated by `pnpm migrate:create`, then trimmed. The generator re-emits
 * every statement from the hand-written migrations since the last snapshot
 * (the video pipeline, the showreel field, the SEO meta fields), all of which
 * are already applied. Those were removed. The rest is the generator's SQL
 * with idempotency guards added, so a re-run is a no-op.
 */

const VERSION_ENUMS: Array<[string, string[]]> = [
  ['enum__leads_v_version_source', ['contact-form', 'homepage', 'cms-page', 'brand-studio', 'lead-magnet', 'newsletter', 'calculator', 'whatsapp', 'other']],
  ['enum__leads_v_version_budget', ['< $2,000', '$2k - $5k', '$5k - $10k', '$10k+']],
  ['enum__leads_v_version_status', ['new', 'contacted', 'qualified', 'won', 'lost', 'archived']],
  ['enum__clients_v_version_deliverables_category', ['design', 'brand', 'documents', 'videos', 'other']],
  ['enum__clients_v_version_service', ['web-design', 'digital-marketing', 'branding', 'video-production', 'seo-paid-ads', 'social-media', 'multiple']],
  ['enum__clients_v_version_pipeline_status', ['lead', 'discovery', 'proposal', 'negotiating', 'won', 'lost', 'on-hold', 'active', 'completed']],
  ['enum__clients_v_version_source', ['website', 'whatsapp', 'referral', 'social', 'walk-in', 'other']],
  ['enum__clients_v_version_project_status', ['onboarding', 'design', 'development', 'review', 'completed', 'retainer']],
  ['enum__invoices_v_version_status', ['pending', 'paid', 'overdue']],
  ['enum_payload_jobs_log_task_slug', ['inline', 'schedulePublish']],
  ['enum_payload_jobs_log_state', ['failed', 'succeeded']],
  ['enum_payload_jobs_task_slug', ['inline', 'schedulePublish']],
]

/** Tables created here, newest dependency last, for the `down` path. */
const NEW_TABLES = [
  '_clients_v_version_timeline',
  '_clients_v_version_deliverables',
  '_invoices_v_version_items',
  'payload_jobs_log',
  '_leads_v',
  '_clients_v',
  '_invoices_v',
  'payload_jobs',
]

/**
 * Column defaults that had drifted from the code. Only the ones the diff
 * flagged, so this list is exactly what is out of step and nothing more.
 */
const DRIFTED_DEFAULTS: Array<[string, string, string]> = [
  ['quaderp_page', 'hero_subtitle', 'Real-time sales tracking, smart inventory management, staff oversight, and theft prevention, all in one powerful platform built for modern retail.'],
  ['quaderp_page', 'features_subtitle', 'Powerful tools designed for retail businesses of every size, from single shops to multi-location chains.'],
  ['video_production_page', 'hero_badge', '✨ AI Video & Reels'],
  ['video_production_page', 'hero_headline', 'AI Video & Reels that keep your brand posting, with no shoot day'],
  ['video_production_page', 'hero_subtitle', 'Every reel is built with AI from your logo, your products and your offer. No camera, no crew, nothing for you to organise. You approve the script, we deliver video you can post the same week.'],
  ['video_production_page', 'services_section_heading', 'What we make'],
  ['video_production_page', 'services_section_subtitle', 'Short-form video for the places your customers actually scroll.'],
  ['video_production_page', 'showreel_subtitle', "A few of the reels we've made recently."],
  ['video_production_page', 'portfolio_gallery_subtitle', 'Recent AI video and reels. Upload the reels themselves, not stills of them.'],
  ['video_production_page', 'process_section_heading', 'How it works'],
  ['video_production_page', 'process_section_subtitle', 'Four steps, no shoot day, and nothing goes out without your sign-off.'],
  ['video_production_page', 'pricing_section_heading', 'AI Video & Reels pricing'],
  ['video_production_page', 'pricing_section_subtitle', 'One batch to try it, or a monthly plan that keeps you posting. Prices in Ghana Cedis, MoMo and bank transfer accepted.'],
  ['video_production_page', 'pricing_section_note', '* One-off packs are billed up front. Monthly plans are billed monthly and you can cancel anytime. Add-ons: paid-ad management (10 to 15% of ad spend) and one-off launch campaigns.'],
  ['video_production_page', 'faq_section_subtitle', 'The questions people actually ask before buying AI video.'],
  ['video_production_page', 'cta_section_heading', 'Ready to stop going quiet?'],
  ['video_production_page', 'cta_section_subtitle', "Book a free 15-minute call. We'll show you exactly what your first three reels would look like, before you pay anything."],
  ['web_design_page', 'showreel_subtitle', 'A taste of our web design projects, from concept to launch.'],
  ['web_design_page', 'cta_section_subtitle', "Book a free web design consultation and let's discuss your project. No commitments, just a conversation about your goals."],
  ['brand_identity_page', 'showreel_subtitle', 'A glimpse of our branding projects, from concept to delivery.'],
  ['brand_identity_page', 'cta_section_subtitle', "Book a free branding consultation and let's discuss your visual identity. No commitments, just a conversation about your goals."],
]

const quote = (value: string) => `'${value.replace(/'/g, "''")}'`

export async function up({ db }: MigrateUpArgs): Promise<void> {
  for (const [name, values] of VERSION_ENUMS) {
    await db.execute(
      sql.raw(`
        DO $$ BEGIN
          CREATE TYPE "public"."${name}" AS ENUM(${values.map(quote).join(', ')});
        EXCEPTION WHEN duplicate_object THEN null; END $$;
      `),
    )
  }

  await db.execute(sql.raw(`
    CREATE TABLE IF NOT EXISTS "_leads_v" (
      "id" serial PRIMARY KEY NOT NULL,
      "parent_id" integer,
      "version_source" "enum__leads_v_version_source",
      "version_magnet_requested" varchar,
      "version_name" varchar NOT NULL,
      "version_email" varchar NOT NULL,
      "version_message" varchar,
      "version_budget" "enum__leads_v_version_budget",
      "version_services_interested" jsonb,
      "version_metadata" jsonb,
      "version_status" "enum__leads_v_version_status" DEFAULT 'new',
      "version_converted_client_id" integer,
      "version_submitted_at" timestamp(3) with time zone,
      "version_updated_at" timestamp(3) with time zone,
      "version_created_at" timestamp(3) with time zone,
      "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
      "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "_clients_v_version_timeline" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" serial PRIMARY KEY NOT NULL,
      "date" timestamp(3) with time zone NOT NULL,
      "title" varchar NOT NULL,
      "description" varchar,
      "_uuid" varchar
    );

    CREATE TABLE IF NOT EXISTS "_clients_v_version_deliverables" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" serial PRIMARY KEY NOT NULL,
      "category" "enum__clients_v_version_deliverables_category" DEFAULT 'other',
      "title" varchar NOT NULL,
      "url" varchar NOT NULL,
      "_uuid" varchar
    );

    CREATE TABLE IF NOT EXISTS "_clients_v" (
      "id" serial PRIMARY KEY NOT NULL,
      "parent_id" integer,
      "version_client_name" varchar NOT NULL,
      "version_contact_name" varchar,
      "version_client_email" varchar,
      "version_phone" varchar,
      "version_service" "enum__clients_v_version_service",
      "version_package" varchar,
      "version_price" numeric,
      "version_start_date" timestamp(3) with time zone,
      "version_pipeline_status" "enum__clients_v_version_pipeline_status" DEFAULT 'lead',
      "version_source" "enum__clients_v_version_source",
      "version_documents_sent_contract" boolean DEFAULT false,
      "version_documents_sent_invoice" boolean DEFAULT false,
      "version_documents_sent_onboarding_email" boolean DEFAULT false,
      "version_documents_sent_setup_instructions" boolean DEFAULT false,
      "version_proposal_url" varchar,
      "version_notes" varchar,
      "version_slug" varchar NOT NULL,
      "version_access_code" varchar NOT NULL,
      "version_project_name" varchar,
      "version_project_status" "enum__clients_v_version_project_status" DEFAULT 'onboarding',
      "version_welcome_message" varchar,
      "version_onboarding_guide_id" integer,
      "version_customizations_duration" numeric,
      "version_customizations_revisions" numeric,
      "version_customizations_deposit_percent" numeric,
      "version_customizations_number_of_pages" numeric,
      "version_customizations_posts_per_month" numeric,
      "version_customizations_platforms" varchar,
      "version_customizations_payment_terms" varchar,
      "version_customizations_extra_deliverables" varchar,
      "version_customizations_special_terms" varchar,
      "version_email_notes_welcome" varchar,
      "version_email_notes_contract" varchar,
      "version_email_notes_setup" varchar,
      "version_email_notes_checkin" varchar,
      "version_updated_at" timestamp(3) with time zone,
      "version_created_at" timestamp(3) with time zone,
      "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
      "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "_invoices_v_version_items" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" serial PRIMARY KEY NOT NULL,
      "description" varchar NOT NULL,
      "quantity" numeric DEFAULT 1 NOT NULL,
      "rate" numeric NOT NULL,
      "_uuid" varchar
    );

    CREATE TABLE IF NOT EXISTS "_invoices_v" (
      "id" serial PRIMARY KEY NOT NULL,
      "parent_id" integer,
      "version_invoice_id" varchar NOT NULL,
      "version_client_id" integer NOT NULL,
      "version_date_issued" timestamp(3) with time zone,
      "version_due_date" timestamp(3) with time zone,
      "version_status" "enum__invoices_v_version_status" DEFAULT 'pending',
      "version_currency" varchar DEFAULT 'USD',
      "version_tax_rate" numeric DEFAULT 0,
      "version_access_token" varchar,
      "version_token_issued_at" timestamp(3) with time zone,
      "version_amount_minor" numeric,
      "version_deposit_percent" numeric DEFAULT 0,
      "version_deposit_minor" numeric,
      "version_amount_paid_minor" numeric DEFAULT 0,
      "version_paid_at" timestamp(3) with time zone,
      "version_paystack_reference" varchar,
      "version_paystack_amount_minor" numeric,
      "version_paystack_status" varchar,
      "version_balance_reference" varchar,
      "version_balance_amount_minor" numeric,
      "version_last_reminder_at" timestamp(3) with time zone,
      "version_reminder_count" numeric DEFAULT 0,
      "version_updated_at" timestamp(3) with time zone,
      "version_created_at" timestamp(3) with time zone,
      "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
      "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "payload_jobs_log" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" varchar PRIMARY KEY NOT NULL,
      "executed_at" timestamp(3) with time zone NOT NULL,
      "completed_at" timestamp(3) with time zone NOT NULL,
      "task_slug" "enum_payload_jobs_log_task_slug" NOT NULL,
      "task_i_d" varchar NOT NULL,
      "input" jsonb,
      "output" jsonb,
      "state" "enum_payload_jobs_log_state" NOT NULL,
      "error" jsonb
    );

    CREATE TABLE IF NOT EXISTS "payload_jobs" (
      "id" serial PRIMARY KEY NOT NULL,
      "input" jsonb,
      "completed_at" timestamp(3) with time zone,
      "total_tried" numeric DEFAULT 0,
      "has_error" boolean DEFAULT false,
      "error" jsonb,
      "task_slug" "enum_payload_jobs_task_slug",
      "queue" varchar DEFAULT 'default',
      "wait_until" timestamp(3) with time zone,
      "processing" boolean DEFAULT false,
      "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
      "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
    );
  `))

  await db.execute(sql.raw(`
    DO $$ BEGIN
      ALTER TABLE "_leads_v" ADD CONSTRAINT "_leads_v_parent_id_leads_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."leads"("id") ON DELETE set null ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN
      ALTER TABLE "_leads_v" ADD CONSTRAINT "_leads_v_version_converted_client_id_clients_id_fk" FOREIGN KEY ("version_converted_client_id") REFERENCES "public"."clients"("id") ON DELETE set null ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN
      ALTER TABLE "_clients_v_version_timeline" ADD CONSTRAINT "_clients_v_version_timeline_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_clients_v"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN
      ALTER TABLE "_clients_v_version_deliverables" ADD CONSTRAINT "_clients_v_version_deliverables_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_clients_v"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN
      ALTER TABLE "_clients_v" ADD CONSTRAINT "_clients_v_parent_id_clients_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."clients"("id") ON DELETE set null ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN
      ALTER TABLE "_clients_v" ADD CONSTRAINT "_clients_v_version_onboarding_guide_id_onboarding_guides_id_fk" FOREIGN KEY ("version_onboarding_guide_id") REFERENCES "public"."onboarding_guides"("id") ON DELETE set null ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN
      ALTER TABLE "_invoices_v_version_items" ADD CONSTRAINT "_invoices_v_version_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_invoices_v"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN
      ALTER TABLE "_invoices_v" ADD CONSTRAINT "_invoices_v_parent_id_invoices_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."invoices"("id") ON DELETE set null ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN
      ALTER TABLE "_invoices_v" ADD CONSTRAINT "_invoices_v_version_client_id_clients_id_fk" FOREIGN KEY ("version_client_id") REFERENCES "public"."clients"("id") ON DELETE set null ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
    DO $$ BEGIN
      ALTER TABLE "payload_jobs_log" ADD CONSTRAINT "payload_jobs_log_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."payload_jobs"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN null; END $$;
  `))

  await db.execute(sql.raw(`
    CREATE INDEX IF NOT EXISTS "_leads_v_parent_idx" ON "_leads_v" USING btree ("parent_id");
    CREATE INDEX IF NOT EXISTS "_leads_v_version_version_converted_client_idx" ON "_leads_v" USING btree ("version_converted_client_id");
    CREATE INDEX IF NOT EXISTS "_leads_v_version_version_updated_at_idx" ON "_leads_v" USING btree ("version_updated_at");
    CREATE INDEX IF NOT EXISTS "_leads_v_version_version_created_at_idx" ON "_leads_v" USING btree ("version_created_at");
    CREATE INDEX IF NOT EXISTS "_leads_v_created_at_idx" ON "_leads_v" USING btree ("created_at");
    CREATE INDEX IF NOT EXISTS "_leads_v_updated_at_idx" ON "_leads_v" USING btree ("updated_at");
    CREATE INDEX IF NOT EXISTS "_clients_v_version_timeline_order_idx" ON "_clients_v_version_timeline" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "_clients_v_version_timeline_parent_id_idx" ON "_clients_v_version_timeline" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "_clients_v_version_deliverables_order_idx" ON "_clients_v_version_deliverables" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "_clients_v_version_deliverables_parent_id_idx" ON "_clients_v_version_deliverables" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "_clients_v_parent_idx" ON "_clients_v" USING btree ("parent_id");
    CREATE INDEX IF NOT EXISTS "_clients_v_version_version_slug_idx" ON "_clients_v" USING btree ("version_slug");
    CREATE INDEX IF NOT EXISTS "_clients_v_version_version_access_code_idx" ON "_clients_v" USING btree ("version_access_code");
    CREATE INDEX IF NOT EXISTS "_clients_v_version_version_onboarding_guide_idx" ON "_clients_v" USING btree ("version_onboarding_guide_id");
    CREATE INDEX IF NOT EXISTS "_clients_v_version_version_updated_at_idx" ON "_clients_v" USING btree ("version_updated_at");
    CREATE INDEX IF NOT EXISTS "_clients_v_version_version_created_at_idx" ON "_clients_v" USING btree ("version_created_at");
    CREATE INDEX IF NOT EXISTS "_clients_v_created_at_idx" ON "_clients_v" USING btree ("created_at");
    CREATE INDEX IF NOT EXISTS "_clients_v_updated_at_idx" ON "_clients_v" USING btree ("updated_at");
    CREATE INDEX IF NOT EXISTS "_invoices_v_version_items_order_idx" ON "_invoices_v_version_items" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "_invoices_v_version_items_parent_id_idx" ON "_invoices_v_version_items" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "_invoices_v_parent_idx" ON "_invoices_v" USING btree ("parent_id");
    CREATE INDEX IF NOT EXISTS "_invoices_v_version_version_invoice_id_idx" ON "_invoices_v" USING btree ("version_invoice_id");
    CREATE INDEX IF NOT EXISTS "_invoices_v_version_version_client_idx" ON "_invoices_v" USING btree ("version_client_id");
    CREATE INDEX IF NOT EXISTS "_invoices_v_version_version_access_token_idx" ON "_invoices_v" USING btree ("version_access_token");
    CREATE INDEX IF NOT EXISTS "_invoices_v_version_version_paystack_reference_idx" ON "_invoices_v" USING btree ("version_paystack_reference");
    CREATE INDEX IF NOT EXISTS "_invoices_v_version_version_balance_reference_idx" ON "_invoices_v" USING btree ("version_balance_reference");
    CREATE INDEX IF NOT EXISTS "_invoices_v_version_version_updated_at_idx" ON "_invoices_v" USING btree ("version_updated_at");
    CREATE INDEX IF NOT EXISTS "_invoices_v_version_version_created_at_idx" ON "_invoices_v" USING btree ("version_created_at");
    CREATE INDEX IF NOT EXISTS "_invoices_v_created_at_idx" ON "_invoices_v" USING btree ("created_at");
    CREATE INDEX IF NOT EXISTS "_invoices_v_updated_at_idx" ON "_invoices_v" USING btree ("updated_at");
    CREATE INDEX IF NOT EXISTS "payload_jobs_log_order_idx" ON "payload_jobs_log" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "payload_jobs_log_parent_id_idx" ON "payload_jobs_log" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "payload_jobs_completed_at_idx" ON "payload_jobs" USING btree ("completed_at");
    CREATE INDEX IF NOT EXISTS "payload_jobs_total_tried_idx" ON "payload_jobs" USING btree ("total_tried");
    CREATE INDEX IF NOT EXISTS "payload_jobs_has_error_idx" ON "payload_jobs" USING btree ("has_error");
    CREATE INDEX IF NOT EXISTS "payload_jobs_task_slug_idx" ON "payload_jobs" USING btree ("task_slug");
    CREATE INDEX IF NOT EXISTS "payload_jobs_queue_idx" ON "payload_jobs" USING btree ("queue");
    CREATE INDEX IF NOT EXISTS "payload_jobs_wait_until_idx" ON "payload_jobs" USING btree ("wait_until");
    CREATE INDEX IF NOT EXISTS "payload_jobs_processing_idx" ON "payload_jobs" USING btree ("processing");
    CREATE INDEX IF NOT EXISTS "payload_jobs_updated_at_idx" ON "payload_jobs" USING btree ("updated_at");
    CREATE INDEX IF NOT EXISTS "payload_jobs_created_at_idx" ON "payload_jobs" USING btree ("created_at");
  `))

  for (const [table, column, value] of DRIFTED_DEFAULTS) {
    await db.execute(
      sql.raw(`ALTER TABLE "${table}" ALTER COLUMN "${column}" SET DEFAULT ${quote(value)};`),
    )
  }
}

/**
 * Drops the tables and enums this migration created. The version tables hold
 * only history, so losing them loses the audit trail and nothing a document
 * needs to render.
 *
 * The drifted defaults are deliberately not reverted. Putting the pre-rename
 * Video Production wording and the em dashes back would undo two separate
 * pieces of finished work to satisfy a symmetry nothing depends on.
 */
export async function down({ db }: MigrateDownArgs): Promise<void> {
  for (const table of [...NEW_TABLES].reverse()) {
    await db.execute(sql.raw(`DROP TABLE IF EXISTS "${table}" CASCADE;`))
  }

  for (const [name] of VERSION_ENUMS) {
    await db.execute(sql.raw(`DROP TYPE IF EXISTS "public"."${name}";`))
  }
}
