name: Deploy Sanity Studio

on:
  push:
    branches:
      - main
    paths:
      - 'studio/**' # Only run when files inside the studio folder change

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'studio/package-lock.json'

      - name: Install Dependencies
        working-directory: ./studio
        run: npm ci

      - name: Deploy to Sanity
        working-directory: ./studio
        env:
          SANITY_AUTH_TOKEN: "${{ secrets.SANITY_AUTH_TOKEN }}"
        run: npx sanity deploy -y
